For Week 4, include concepts such as logistic regression and feature scaling. This homework should be submitted for peer review in the assignment titled 4.3 Peer Review: Week 4 Jupyter Notebook. Complete and submit your Jupyter Notebook homework by 11:59pm ET on Sunday.

In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler

In [23]:
random_state = 42
classification_reports = []
classification_report_keys = []

## Import Data

In [24]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

## Undersampling due to heavy class imbalance

In [25]:
from collections import Counter


X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(sampling_strategy=0.1, random_state=random_state)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 4920, 1: 492})

## Split Data

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

## Baseline Logistic Regression
#### (No feature scaling)

In [27]:
model = LogisticRegression(max_iter=10_000, random_state=random_state) # Default max_iter was not converging

In [28]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000, random_state=42)

In [29]:
y_pred = model.predict(X_test)

In [30]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Baseline Logsitic Regression')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       985
           1       0.95      0.89      0.92        98

    accuracy                           0.99      1083
   macro avg       0.97      0.94      0.95      1083
weighted avg       0.98      0.99      0.99      1083

## Feature Scaling + Logistic Regression

In [31]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [32]:
model = LogisticRegression(max_iter=10_000, random_state=random_state) # Default max_iter was not converging

In [33]:
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=10000, random_state=42)

In [34]:
y_pred = model.predict(X_test_scaled)

In [35]:
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()
classification_reports.append(df_temp)
classification_report_keys.append('Logsitic Regression with Standard Scaling')

print(classification_report(y_true=y_test, y_pred=y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       985
           1       0.96      0.89      0.92        98

    accuracy                           0.99      1083
   macro avg       0.97      0.94      0.96      1083
weighted avg       0.99      0.99      0.99      1083

## Conclusions

In [36]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                        precision  ...      support
Baseline Logsitic Regression              0              0.988900  ...   985.000000
                                          1              0.945652  ...    98.000000
                                          accuracy       0.985226  ...     0.985226
                                          macro avg      0.967276  ...  1083.000000
                                          weighted avg   0.984987  ...  1083.000000
Logsitic Regression with Standard Scaling 0              0.988911  ...   985.000000
                                          1              0.956044  ...    98.000000
                                          accuracy       0.986150  ...     0.986150
                                          macro avg      0.972478  ...  1083.000000
                                          weighted avg   0.985937  ...  1083.000000

[10 rows x 4 columns]

We can see strong performance in both the baseline and feature scaled models. This was expected behavior to me since all V features (e.g. V1, V2) are preprocessed to be PCA transformed to protect client confidentiality. As a result, these features are already scaled and transformed. The only features affected by scaling are the Amount and Time features which are both numeric. The scaling of these two features could have been the cause of the slight lift in performance (0.953 -> 0.956 macro avg f1-score, 0.9413 -> 0.9418 macro avg recall and finally 0.9672 -> 0.9724 macro avg precision). These differences are very small, but could be impactful when utilizing models on credit card fraud which is extremely high volume transactions.