Support vector machines, the kernel trick, and regularization for support vector machines

In [45]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [46]:
random_state=42

## IBM

In [47]:
classification_reports = []
classification_report_keys = []

### Data

In [48]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [49]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

### Undersampling

In [50]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 5177, 1: 5177})

### Split Data

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [52]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [53]:
model.fit(X_train, y_train)

SVC()

In [54]:
y_pred = model.predict(X_test)

In [55]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1036
           1       0.50      0.00      0.00      1035

    accuracy                           0.50      2071
   macro avg       0.50      0.50      0.33      2071
weighted avg       0.50      0.50      0.33      2071

We see poor performance on the positive class, with 0% recall/f1. This could be due to the linear kernal choice or a lack of feature scaling. We can test this assumption during hyper-parameter tuning

### Feature Scaling

In [56]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [57]:
model.fit(X_train_scaled, y_train)

SVC()

In [58]:
y_pred = model.predict(X_test_scaled)

In [59]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.89      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

Once feature scaling is applied, recall on positive class jumps from 0% to 88%. This shows that feature scaling was critical for the model. We can attempt to further boost performance with hyperparameter tuning

### Parameter Tuning

In [60]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [61]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-24 20:10:28,737] A new study created in memory with name: no-name-9b45f8a1-4aaf-4083-9dbd-9e52aebb1298
[I 2026-06-24 20:10:31,998] Trial 0 finished with value: 0.8592489641789479 and parameters: {'C': 0.22245793685476278, 'kernel': 'rbf', 'coef0': 0.1253019167260908, 'Class_weight': None}. Best is trial 0 with value: 0.8592489641789479.
[I 2026-06-24 20:10:34,238] Trial 1 finished with value: 0.8597317645961902 and parameters: {'C': 0.5832348431967431, 'kernel': 'rbf', 'coef0': 0.21630519751493105, 'Class_weight': None}. Best is trial 1 with value: 0.8597317645961902.
[I 2026-06-24 20:10:36,424] Trial 2 finished with value: 0.8445210748063847 and parameters: {'C': 0.3667669958645376, 'kernel': 'sigmoid', 'coef0': 0.5568572516190483, 'Class_weight': None}. Best is trial 1 with value: 0.8597317645961902.
[I 2026-06-24 20:10:38,860] Trial 3 finished with value: 0.8597317645961902 and parameters: {'C': 0.43445589741470186, 'kernel': 'rbf', 'coef0': 0.2357354796143274, 'Class_weight': None}. Best is trial 1 with value: 0.8597317645961902.
[I 2026-06-24 20:10:40,143] Trial 4 finished with value: 0.8597317645961902 and parameters: {'C': 0.608893296484695, 'kernel': 'rbf', 'coef0': 0.3646398339979422, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8597317645961902.
[I 2026-06-24 20:10:41,733] Trial 5 finished with value: 0.8592489641789479 and parameters: {'C': 0.20109678497636935, 'kernel': 'rbf', 'coef0': 0.09619688237922464, 'Class_weight': None}. Best is trial 1 with value: 0.8597317645961902.
[I 2026-06-24 20:10:43,022] Trial 6 finished with value: 0.8599733104899098 and parameters: {'C': 0.9110861144526934, 'kernel': 'rbf', 'coef0': 0.46771103137731707, 'Class_weight': None}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:44,088] Trial 7 finished with value: 0.8172365867729585 and parameters: {'C': 0.33584107330146795, 'kernel': 'sigmoid', 'coef0': 0.378989203161203, 'Class_weight': None}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:45,628] Trial 8 finished with value: 0.8592489641789479 and parameters: {'C': 0.20802688272197495, 'kernel': 'rbf', 'coef0': 0.7267590391660371, 'Class_weight': 'balanced'}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:46,758] Trial 9 finished with value: 0.8597317645961902 and parameters: {'C': 0.7246352289925068, 'kernel': 'rbf', 'coef0': 0.7251295989372285, 'Class_weight': 'balanced'}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:48,068] Trial 10 finished with value: 0.804193691252484 and parameters: {'C': 0.9364267246464087, 'kernel': 'sigmoid', 'coef0': 0.9838698678351929, 'Class_weight': 'balanced'}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:49,302] Trial 11 finished with value: 0.8599733104899098 and parameters: {'C': 0.9943595402373577, 'kernel': 'rbf', 'coef0': 0.5120990462544567, 'Class_weight': None}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:50,368] Trial 12 finished with value: 0.8599733104899098 and parameters: {'C': 0.9484260470582946, 'kernel': 'rbf', 'coef0': 0.5665997021893918, 'Class_weight': None}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:51,501] Trial 13 finished with value: 0.8599733104899098 and parameters: {'C': 0.841165893667968, 'kernel': 'rbf', 'coef0': 0.6945356095262918, 'Class_weight': None}. Best is trial 6 with value: 0.8599733104899098.
[I 2026-06-24 20:10:54,302] Trial 14 finished with value: 0.8621469321631906 and parameters: {'C': 0.004492606862085746, 'kernel': 'sigmoid', 'coef0': 0.44451421950358627, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:10:56,055] Trial 15 finished with value: 0.8621469321631906 and parameters: {'C': 0.021687664094734882, 'kernel': 'sigmoid', 'coef0': 0.3430816667548613, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:10:57,681] Trial 16 finished with value: 0.8621469321631906 and parameters: {'C': 0.025062171213954577, 'kernel': 'sigmoid', 'coef0': 0.33371641826755394, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:00,225] Trial 17 finished with value: 0.8621469321631906 and parameters: {'C': 0.019668995745841942, 'kernel': 'sigmoid', 'coef0': 0.9890387652786194, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:01,470] Trial 18 finished with value: 0.8594908014428653 and parameters: {'C': 0.1263195835562554, 'kernel': 'sigmoid', 'coef0': 0.008597502382238165, 'Class_weight': 'balanced'}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:02,581] Trial 19 finished with value: 0.8597323473365851 and parameters: {'C': 0.10278169941983967, 'kernel': 'sigmoid', 'coef0': 0.2539986462648841, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:03,944] Trial 20 finished with value: 0.8544174635641568 and parameters: {'C': 0.30115500660839417, 'kernel': 'sigmoid', 'coef0': 0.8559421584573316, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:06,436] Trial 21 finished with value: 0.8621469321631906 and parameters: {'C': 0.005869115261448173, 'kernel': 'sigmoid', 'coef0': 0.3714301587135415, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:07,620] Trial 22 finished with value: 0.8594910928130627 and parameters: {'C': 0.09679082359897753, 'kernel': 'sigmoid', 'coef0': 0.4361188321534628, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:09,591] Trial 23 finished with value: 0.8621469321631906 and parameters: {'C': 0.010878521757432555, 'kernel': 'sigmoid', 'coef0': 0.29172855542777676, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:10,940] Trial 24 finished with value: 0.8621466407929932 and parameters: {'C': 0.1350325160967265, 'kernel': 'sigmoid', 'coef0': 0.6366409906854773, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:12,065] Trial 25 finished with value: 0.8215812077877427 and parameters: {'C': 0.2545397047461765, 'kernel': 'sigmoid', 'coef0': 0.31439614357267015, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:13,388] Trial 26 finished with value: 0.8602154391240247 and parameters: {'C': 0.06528382984659012, 'kernel': 'sigmoid', 'coef0': 0.4325323252032187, 'Class_weight': 'balanced'}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:14,523] Trial 27 finished with value: 0.850315262553685 and parameters: {'C': 0.17141796350986968, 'kernel': 'sigmoid', 'coef0': 0.18533246259825226, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:15,609] Trial 28 finished with value: 0.8264083378495712 and parameters: {'C': 0.47222711476291274, 'kernel': 'sigmoid', 'coef0': 0.32129058910980657, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:16,653] Trial 29 finished with value: 0.8056525818313199 and parameters: {'C': 0.2683927401325658, 'kernel': 'sigmoid', 'coef0': 0.11539923719369582, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:17,664] Trial 30 finished with value: 0.8058979155376071 and parameters: {'C': 0.38753049974920095, 'kernel': 'sigmoid', 'coef0': 0.1585030609446086, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:19,283] Trial 31 finished with value: 0.8616644231161459 and parameters: {'C': 0.06532882239661904, 'kernel': 'sigmoid', 'coef0': 0.855855905879844, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:21,825] Trial 32 finished with value: 0.8621469321631906 and parameters: {'C': 0.006501511365143431, 'kernel': 'sigmoid', 'coef0': 0.5250302806755962, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:23,179] Trial 33 finished with value: 0.860456693647547 and parameters: {'C': 0.06388962048808355, 'kernel': 'sigmoid', 'coef0': 0.6135858499147369, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:24,555] Trial 34 finished with value: 0.8568329225013549 and parameters: {'C': 0.1675634550525946, 'kernel': 'sigmoid', 'coef0': 0.414496082819007, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:25,847] Trial 35 finished with value: 0.860456693647547 and parameters: {'C': 0.04663055412447583, 'kernel': 'sigmoid', 'coef0': 0.2767314086762609, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:27,239] Trial 36 finished with value: 0.8184265426595105 and parameters: {'C': 0.5465448998707466, 'kernel': 'sigmoid', 'coef0': 0.9782033658575365, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:28,423] Trial 37 finished with value: 0.8500783785831251 and parameters: {'C': 0.14667665370460292, 'kernel': 'sigmoid', 'coef0': 0.47964187889060744, 'Class_weight': None}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:29,458] Trial 38 finished with value: 0.8066106070406693 and parameters: {'C': 0.23164408672904488, 'kernel': 'sigmoid', 'coef0': 0.22608871723696922, 'Class_weight': 'balanced'}. Best is trial 14 with value: 0.8621469321631906.
[I 2026-06-24 20:11:31,992] Trial 39 finished with value: 0.8991019970513335 and parameters: {'C': 0.002334785038316578, 'kernel': 'sigmoid', 'coef0': 0.34976271334848846, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:32,987] Trial 40 finished with value: 0.8095176075010343 and parameters: {'C': 0.6898400848895622, 'kernel': 'sigmoid', 'coef0': 0.3501829997077303, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:34,555] Trial 41 finished with value: 0.861663840375751 and parameters: {'C': 0.04322277631159761, 'kernel': 'sigmoid', 'coef0': 0.41517139942960146, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:35,725] Trial 42 finished with value: 0.8597323473365851 and parameters: {'C': 0.10089493468986847, 'kernel': 'sigmoid', 'coef0': 0.3492871970322232, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:38,229] Trial 43 finished with value: 0.8650440260368409 and parameters: {'C': 0.0028061679972760795, 'kernel': 'sigmoid', 'coef0': 0.20062191380593808, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:39,305] Trial 44 finished with value: 0.8051750260776327 and parameters: {'C': 0.1918797675717134, 'kernel': 'sigmoid', 'coef0': 0.08184613740181307, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:40,867] Trial 45 finished with value: 0.8418611562734917 and parameters: {'C': 0.0685942191954015, 'kernel': 'rbf', 'coef0': 0.18505360072551524, 'Class_weight': 'balanced'}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:42,043] Trial 46 finished with value: 0.8594908014428653 and parameters: {'C': 0.11144992186287009, 'kernel': 'sigmoid', 'coef0': 0.24334238214817905, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:44,734] Trial 47 finished with value: 0.8621469321631906 and parameters: {'C': 0.0050948369776065835, 'kernel': 'sigmoid', 'coef0': 0.061648790477005666, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:46,127] Trial 48 finished with value: 0.8592489641789479 and parameters: {'C': 0.21009473206703835, 'kernel': 'rbf', 'coef0': 0.39827593890264074, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:47,199] Trial 49 finished with value: 0.8087798581609877 and parameters: {'C': 0.3874647825437207, 'kernel': 'sigmoid', 'coef0': 0.4559325874447215, 'Class_weight': 'balanced'}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:48,479] Trial 50 finished with value: 0.859008001025623 and parameters: {'C': 0.14580251656621487, 'kernel': 'sigmoid', 'coef0': 0.5728971781404435, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:49,838] Trial 51 finished with value: 0.8611813313287063 and parameters: {'C': 0.03993752907525632, 'kernel': 'sigmoid', 'coef0': 0.3256921456974001, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:51,058] Trial 52 finished with value: 0.8599736018601074 and parameters: {'C': 0.09138937691396828, 'kernel': 'sigmoid', 'coef0': 0.5060899087500259, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:52,710] Trial 53 finished with value: 0.8621469321631906 and parameters: {'C': 0.02818296751875749, 'kernel': 'sigmoid', 'coef0': 0.2793509031829472, 'Class_weight': None}. Best is trial 39 with value: 0.8991019970513335.
[I 2026-06-24 20:11:55,548] Trial 54 finished with value: 0.9435464414957782 and parameters: {'C': 0.0020606237868059183, 'kernel': 'sigmoid', 'coef0': 0.37497907045511536, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:11:57,111] Trial 55 finished with value: 0.8493490789788056 and parameters: {'C': 0.086546078425485, 'kernel': 'rbf', 'coef0': 0.38842130950522497, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:11:58,061] Trial 56 finished with value: 0.798403874058146 and parameters: {'C': 0.8200760167244885, 'kernel': 'sigmoid', 'coef0': 0.20016048298319067, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:11:59,188] Trial 57 finished with value: 0.85369369999359 and parameters: {'C': 0.12487377621395351, 'kernel': 'sigmoid', 'coef0': 0.1560365477171637, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:01,868] Trial 58 finished with value: 0.9435464414957782 and parameters: {'C': 0.0018229341878746544, 'kernel': 'sigmoid', 'coef0': 0.3622064067709765, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:04,474] Trial 59 finished with value: 0.8621469321631906 and parameters: {'C': 0.004238162097822709, 'kernel': 'sigmoid', 'coef0': 0.47596212094707707, 'Class_weight': 'balanced'}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:05,756] Trial 60 finished with value: 0.8597317645961902 and parameters: {'C': 0.3101204807197447, 'kernel': 'rbf', 'coef0': 0.5389664958418272, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:07,041] Trial 61 finished with value: 0.8611813313287063 and parameters: {'C': 0.04251210774217909, 'kernel': 'sigmoid', 'coef0': 0.3520305978752296, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:08,159] Trial 62 finished with value: 0.8597323473365851 and parameters: {'C': 0.07664507709909933, 'kernel': 'sigmoid', 'coef0': 0.29894203198249414, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:10,678] Trial 63 finished with value: 0.9435464414957782 and parameters: {'C': 0.001957951759225945, 'kernel': 'sigmoid', 'coef0': 0.4484658785400317, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:12,198] Trial 64 finished with value: 0.8621469321631906 and parameters: {'C': 0.03552280288789629, 'kernel': 'sigmoid', 'coef0': 0.44439217527027414, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:15,228] Trial 65 finished with value: 0.9435464414957782 and parameters: {'C': 0.00111443021422662, 'kernel': 'sigmoid', 'coef0': 0.3838361806192468, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:16,508] Trial 66 finished with value: 0.8597323473365851 and parameters: {'C': 0.11147140507857964, 'kernel': 'sigmoid', 'coef0': 0.3865147881122076, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:17,741] Trial 67 finished with value: 0.8563515789351002 and parameters: {'C': 0.16693415911573511, 'kernel': 'sigmoid', 'coef0': 0.4898831517897604, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:19,057] Trial 68 finished with value: 0.8599738932303049 and parameters: {'C': 0.06030843442948176, 'kernel': 'sigmoid', 'coef0': 0.2598893995439092, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:21,915] Trial 69 finished with value: 0.8988610338980088 and parameters: {'C': 0.0029392138952031113, 'kernel': 'sigmoid', 'coef0': 0.5829374716992208, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:25,087] Trial 70 finished with value: 0.8633537875211971 and parameters: {'C': 0.004205044510246475, 'kernel': 'sigmoid', 'coef0': 0.5727293444187099, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:27,795] Trial 71 finished with value: 0.8621469321631906 and parameters: {'C': 0.00465452222124667, 'kernel': 'sigmoid', 'coef0': 0.597749516725209, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:29,590] Trial 72 finished with value: 0.8614225858522285 and parameters: {'C': 0.038551497670743055, 'kernel': 'sigmoid', 'coef0': 0.6696800491402886, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:31,046] Trial 73 finished with value: 0.860456693647547 and parameters: {'C': 0.0821740660523923, 'kernel': 'sigmoid', 'coef0': 0.6441965334128619, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:32,497] Trial 74 finished with value: 0.8614225858522285 and parameters: {'C': 0.056609242809254896, 'kernel': 'sigmoid', 'coef0': 0.558693227527202, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:34,433] Trial 75 finished with value: 0.8621469321631906 and parameters: {'C': 0.023610747500387785, 'kernel': 'sigmoid', 'coef0': 0.41107427024556425, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:35,813] Trial 76 finished with value: 0.8599733104899098 and parameters: {'C': 0.13569123102372588, 'kernel': 'sigmoid', 'coef0': 0.5265352453458158, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:37,339] Trial 77 finished with value: 0.8664880567356048 and parameters: {'C': 0.0942089077429635, 'kernel': 'sigmoid', 'coef0': 0.7390159061310461, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:38,874] Trial 78 finished with value: 0.860456693647547 and parameters: {'C': 0.08942296384925036, 'kernel': 'sigmoid', 'coef0': 0.837608669840808, 'Class_weight': 'balanced'}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:40,657] Trial 79 finished with value: 0.8220648823155772 and parameters: {'C': 0.05712639110274158, 'kernel': 'rbf', 'coef0': 0.36696861036818684, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:41,984] Trial 80 finished with value: 0.8498345017278253 and parameters: {'C': 0.44962056619492785, 'kernel': 'sigmoid', 'coef0': 0.754236895677411, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.
[I 2026-06-24 20:12:44,294] Trial 81 finished with value: 0.8614222944820312 and parameters: {'C': 0.02703319091782111, 'kernel': 'sigmoid', 'coef0': 0.7076299497969296, 'Class_weight': None}. Best is trial 54 with value: 0.9435464414957782.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
54,54,0.943546,2026-06-24 20:11:52.710444,2026-06-24 20:11:55.548319,0 days 00:00:02.837875,0.002061,None,0.374979,sigmoid,COMPLETE
58,58,0.943546,2026-06-24 20:11:59.189440,2026-06-24 20:12:01.868369,0 days 00:00:02.678929,0.001823,None,0.362206,sigmoid,COMPLETE
65,65,0.943546,2026-06-24 20:12:12.198354,2026-06-24 20:12:15.228667,0 days 00:00:03.030313,0.001114,None,0.383836,sigmoid,COMPLETE
63,63,0.943546,2026-06-24 20:12:08.160440,2026-06-24 20:12:10.678552,0 days 00:00:02.518112,0.001958,None,0.448466,sigmoid,COMPLETE
83,83,0.943064,2026-06-24 20:12:47.569306,2026-06-24 20:12:50.676542,0 days 00:00:03.107236,0.003031,None,0.771649,sigmoid,COMPLETE

## Credit Card

In [62]:
classification_reports = []
classification_report_keys = []

### Data

In [63]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling

In [64]:
from collections import Counter


X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 492, 1: 492})

### Split Data

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [66]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [67]:
model.fit(X_train, y_train)

SVC()

In [68]:
y_pred = model.predict(X_test)

In [69]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.54      0.49      0.52        99
           1       0.53      0.57      0.55        98

    accuracy                           0.53       197
   macro avg       0.53      0.53      0.53       197
weighted avg       0.53      0.53      0.53       197

We see poor performance with macro avg f1 of 0.53 and consistent performance across positive and negative class. This could be due to the linear kernal choice or a lack of feature scaling. We can test this assumption during hyper-parameter tuning

### Feature Scaling

In [70]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [71]:
model.fit(X_train_scaled, y_train)

SVC()

In [72]:
y_pred = model.predict(X_test_scaled)

In [73]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.94      0.99      0.97        99
           1       0.99      0.94      0.96        98

    accuracy                           0.96       197
   macro avg       0.97      0.96      0.96       197
weighted avg       0.97      0.96      0.96       197

Once feature scaling is applied, recall on positive class jumps from ~50% to 96%. This shows that feature scaling was critical for the model. We can attempt to further boost performance with hyperparameter tuning

### Parameter Tuning

In [74]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [75]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-24 20:13:20,751] A new study created in memory with name: no-name-0da5b139-c529-45b2-b2ff-0f62a8480afa
[I 2026-06-24 20:13:20,777] Trial 0 finished with value: 0.8122687439143135 and parameters: {'C': 0.04170726563450069, 'kernel': 'rbf', 'coef0': 0.47488710624729347, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8122687439143135.
[I 2026-06-24 20:13:20,793] Trial 1 finished with value: 0.8122038299253489 and parameters: {'C': 0.28985269487989923, 'kernel': 'sigmoid', 'coef0': 0.23741878351181067, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8122687439143135.
[I 2026-06-24 20:13:20,808] Trial 2 finished with value: 0.8679974034404415 and parameters: {'C': 0.8413310107526579, 'kernel': 'rbf', 'coef0': 0.2845277791280214, 'Class_weight': None}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,825] Trial 3 finished with value: 0.8172995780590717 and parameters: {'C': 0.8550742065545504, 'kernel': 'sigmoid', 'coef0': 0.6460522384579611, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,847] Trial 4 finished with value: 0.8147679324894515 and parameters: {'C': 0.9783851951569102, 'kernel': 'sigmoid', 'coef0': 0.8578507726607022, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,863] Trial 5 finished with value: 0.8603375527426161 and parameters: {'C': 0.5820835847439377, 'kernel': 'rbf', 'coef0': 0.3107423296904065, 'Class_weight': None}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,879] Trial 6 finished with value: 0.8096721843557286 and parameters: {'C': 0.35175788310654454, 'kernel': 'sigmoid', 'coef0': 0.5861320881817375, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,894] Trial 7 finished with value: 0.8248945147679325 and parameters: {'C': 0.6668182107699979, 'kernel': 'sigmoid', 'coef0': 0.4465514974716748, 'Class_weight': None}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,926] Trial 8 finished with value: 0.8299902629016553 and parameters: {'C': 0.07220778592490455, 'kernel': 'rbf', 'coef0': 0.1962641630939984, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,941] Trial 9 finished with value: 0.8045764362220058 and parameters: {'C': 0.7185158743916978, 'kernel': 'sigmoid', 'coef0': 0.9970230594739756, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8679974034404415.
[I 2026-06-24 20:13:20,956] Trial 10 finished with value: 0.8705290490100618 and parameters: {'C': 0.8650909919916013, 'kernel': 'rbf', 'coef0': 0.01898605971089884, 'Class_weight': None}. Best is trial 10 with value: 0.8705290490100618.
[I 2026-06-24 20:13:20,972] Trial 11 finished with value: 0.8730606945796818 and parameters: {'C': 0.9988608523778009, 'kernel': 'rbf', 'coef0': 0.020735927896390338, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:20,987] Trial 12 finished with value: 0.8730606945796818 and parameters: {'C': 0.9856201047438782, 'kernel': 'rbf', 'coef0': 0.010785592884942666, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,003] Trial 13 finished with value: 0.8730606945796818 and parameters: {'C': 0.9775395409625656, 'kernel': 'rbf', 'coef0': 0.026490826111378242, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,031] Trial 14 finished with value: 0.8502109704641351 and parameters: {'C': 0.43232750480840976, 'kernel': 'rbf', 'coef0': 0.12297992105922534, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,047] Trial 15 finished with value: 0.8654657578708213 and parameters: {'C': 0.7452225088873813, 'kernel': 'rbf', 'coef0': 0.06791609857195265, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,062] Trial 16 finished with value: 0.8730606945796818 and parameters: {'C': 0.9967749998944214, 'kernel': 'rbf', 'coef0': 0.37977995401254155, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,078] Trial 17 finished with value: 0.8578059071729959 and parameters: {'C': 0.5585907638282467, 'kernel': 'rbf', 'coef0': 0.15737754835174858, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,094] Trial 18 finished with value: 0.8451801363193769 and parameters: {'C': 0.17913741503512903, 'kernel': 'rbf', 'coef0': 0.6832697999948159, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,109] Trial 19 finished with value: 0.8654657578708213 and parameters: {'C': 0.8057795691172107, 'kernel': 'rbf', 'coef0': 0.12999935104544422, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,139] Trial 20 finished with value: 0.8629016553067187 and parameters: {'C': 0.6405650955801784, 'kernel': 'rbf', 'coef0': 0.3629851818422313, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,160] Trial 21 finished with value: 0.8730606945796818 and parameters: {'C': 0.9311364277352654, 'kernel': 'rbf', 'coef0': 0.03539318720089435, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,178] Trial 22 finished with value: 0.8730606945796818 and parameters: {'C': 0.9173511329544861, 'kernel': 'rbf', 'coef0': 0.05539796422342406, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,194] Trial 23 finished with value: 0.8730606945796818 and parameters: {'C': 0.9731453565604837, 'kernel': 'rbf', 'coef0': 0.01622013650880953, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,225] Trial 24 finished with value: 0.8654657578708213 and parameters: {'C': 0.7826410157623775, 'kernel': 'rbf', 'coef0': 0.12064484280315711, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,251] Trial 25 finished with value: 0.8679974034404415 and parameters: {'C': 0.8784400225925055, 'kernel': 'rbf', 'coef0': 0.19838091873780678, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,266] Trial 26 finished with value: 0.8730606945796818 and parameters: {'C': 0.990536111054295, 'kernel': 'rbf', 'coef0': 0.2662066614923049, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,291] Trial 27 finished with value: 0.8629016553067187 and parameters: {'C': 0.7134488667553425, 'kernel': 'rbf', 'coef0': 0.08820534703526811, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,319] Trial 28 finished with value: 0.8679974034404415 and parameters: {'C': 0.8747090341466752, 'kernel': 'rbf', 'coef0': 0.001924551844113262, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,350] Trial 29 finished with value: 0.8502109704641351 and parameters: {'C': 0.49576414533709073, 'kernel': 'rbf', 'coef0': 0.5309302805065689, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,381] Trial 30 finished with value: 0.8730606945796818 and parameters: {'C': 0.9179660340191029, 'kernel': 'rbf', 'coef0': 0.186613807620686, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,397] Trial 31 finished with value: 0.8730606945796818 and parameters: {'C': 0.9962311949910329, 'kernel': 'rbf', 'coef0': 0.3889193116053515, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,427] Trial 32 finished with value: 0.8730606945796818 and parameters: {'C': 0.9298300311033634, 'kernel': 'rbf', 'coef0': 0.3535975961110335, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,453] Trial 33 finished with value: 0.8654657578708213 and parameters: {'C': 0.793197109816206, 'kernel': 'rbf', 'coef0': 0.25246561379977767, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,469] Trial 34 finished with value: 0.8248945147679325 and parameters: {'C': 0.9958241356418444, 'kernel': 'sigmoid', 'coef0': 0.7808117726752855, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,485] Trial 35 finished with value: 0.8654657578708213 and parameters: {'C': 0.8253650105848029, 'kernel': 'rbf', 'coef0': 0.4625150828208243, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,524] Trial 36 finished with value: 0.8730606945796818 and parameters: {'C': 0.9266428924203495, 'kernel': 'rbf', 'coef0': 0.07505134387247872, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,540] Trial 37 finished with value: 0.840084388185654 and parameters: {'C': 0.8749745356050711, 'kernel': 'sigmoid', 'coef0': 0.22520077237597694, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,557] Trial 38 finished with value: 0.8451476793248947 and parameters: {'C': 0.2992233710256489, 'kernel': 'rbf', 'coef0': 0.5434178059852138, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,573] Trial 39 finished with value: 0.840084388185654 and parameters: {'C': 0.76651894712559, 'kernel': 'sigmoid', 'coef0': 0.15467595927629021, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,596] Trial 40 finished with value: 0.8730606945796818 and parameters: {'C': 0.9523800510350214, 'kernel': 'rbf', 'coef0': 0.31378425082908923, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,632] Trial 41 finished with value: 0.8730606945796818 and parameters: {'C': 0.9260346131308328, 'kernel': 'rbf', 'coef0': 0.04665613650892678, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,647] Trial 42 finished with value: 0.8679974034404415 and parameters: {'C': 0.8425667276945025, 'kernel': 'rbf', 'coef0': 0.09794111219821448, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,677] Trial 43 finished with value: 0.8730606945796818 and parameters: {'C': 0.9539399425991893, 'kernel': 'rbf', 'coef0': 0.005839706812969903, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,693] Trial 44 finished with value: 0.8679974034404415 and parameters: {'C': 0.8968309696269516, 'kernel': 'rbf', 'coef0': 0.6279841584371656, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,716] Trial 45 finished with value: 0.8451476793248945 and parameters: {'C': 0.9981330240022448, 'kernel': 'sigmoid', 'coef0': 0.05571065002554111, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,747] Trial 46 finished with value: 0.8654657578708213 and parameters: {'C': 0.8240534859384209, 'kernel': 'rbf', 'coef0': 0.1454259446249439, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,763] Trial 47 finished with value: 0.8730606945796818 and parameters: {'C': 0.9540852553085485, 'kernel': 'rbf', 'coef0': 0.7246317599228435, 'Class_weight': None}. Best is trial 11 with value: 0.8730606945796818.
[I 2026-06-24 20:13:21,795] Trial 48 finished with value: 0.9012658227848102 and parameters: {'C': 0.0014695513347025013, 'kernel': 'rbf', 'coef0': 0.931381310125909, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,825] Trial 49 finished with value: 0.8401168451801364 and parameters: {'C': 0.15735885732445537, 'kernel': 'rbf', 'coef0': 0.9176255644902853, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,846] Trial 50 finished with value: 0.6522882181110029 and parameters: {'C': 0.053832592295258386, 'kernel': 'sigmoid', 'coef0': 0.9895857516102112, 'Class_weight': 'balanced'}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,861] Trial 51 finished with value: 0.8502109704641351 and parameters: {'C': 0.36548285921237533, 'kernel': 'rbf', 'coef0': 0.037850154324200094, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,893] Trial 52 finished with value: 0.8502434274586174 and parameters: {'C': 0.21006105411902598, 'kernel': 'rbf', 'coef0': 0.0990142312136518, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,924] Trial 53 finished with value: 0.8325219084712756 and parameters: {'C': 0.10343627439744009, 'kernel': 'rbf', 'coef0': 0.7626331636869828, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,954] Trial 54 finished with value: 0.8629016553067187 and parameters: {'C': 0.6557893281158195, 'kernel': 'rbf', 'coef0': 0.8718325335998494, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:21,970] Trial 55 finished with value: 0.8603375527426161 and parameters: {'C': 0.5865172143778705, 'kernel': 'rbf', 'coef0': 0.42495241982766635, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,000] Trial 56 finished with value: 0.7309639727361247 and parameters: {'C': 0.01404910090435878, 'kernel': 'rbf', 'coef0': 0.30588866235174683, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,016] Trial 57 finished with value: 0.8502109704641351 and parameters: {'C': 0.46901345672079986, 'kernel': 'rbf', 'coef0': 0.11472630807704942, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,046] Trial 58 finished with value: 0.8679974034404415 and parameters: {'C': 0.8971997137104615, 'kernel': 'rbf', 'coef0': 0.21492100496170222, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,062] Trial 59 finished with value: 0.8629016553067187 and parameters: {'C': 0.7185744636885566, 'kernel': 'rbf', 'coef0': 0.597096303171498, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,092] Trial 60 finished with value: 0.8730606945796818 and parameters: {'C': 0.9631968734718139, 'kernel': 'rbf', 'coef0': 0.1726170720910248, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,107] Trial 61 finished with value: 0.8730606945796818 and parameters: {'C': 0.9144079717995351, 'kernel': 'rbf', 'coef0': 0.04152241155483999, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,138] Trial 62 finished with value: 0.8679974034404415 and parameters: {'C': 0.8516409163883547, 'kernel': 'rbf', 'coef0': 0.07226511639868322, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,168] Trial 63 finished with value: 0.8730606945796818 and parameters: {'C': 0.9594911205972954, 'kernel': 'rbf', 'coef0': 0.007135973379479233, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,184] Trial 64 finished with value: 0.8679974034404415 and parameters: {'C': 0.8912141022025515, 'kernel': 'rbf', 'coef0': 0.03828416688175425, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,200] Trial 65 finished with value: 0.8730606945796818 and parameters: {'C': 0.940735634319235, 'kernel': 'rbf', 'coef0': 0.1292528933101961, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,230] Trial 66 finished with value: 0.8502109704641351 and parameters: {'C': 0.40934943069627755, 'kernel': 'rbf', 'coef0': 0.5003061172570792, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,246] Trial 67 finished with value: 0.8730606945796818 and parameters: {'C': 0.9880243839552182, 'kernel': 'rbf', 'coef0': 0.07902155211918202, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,262] Trial 68 finished with value: 0.7919182083739045 and parameters: {'C': 0.25887396349283387, 'kernel': 'sigmoid', 'coef0': 0.6863758194034524, 'Class_weight': 'balanced'}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,292] Trial 69 finished with value: 0.8705290490100618 and parameters: {'C': 0.8563621394516228, 'kernel': 'rbf', 'coef0': 0.031700488340526536, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,323] Trial 70 finished with value: 0.8654657578708213 and parameters: {'C': 0.8137756631712774, 'kernel': 'rbf', 'coef0': 0.0028915813263568763, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,349] Trial 71 finished with value: 0.8730606945796818 and parameters: {'C': 0.9702627069581506, 'kernel': 'rbf', 'coef0': 0.06692492247759019, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,364] Trial 72 finished with value: 0.8705290490100616 and parameters: {'C': 0.9077376994652827, 'kernel': 'rbf', 'coef0': 0.0979686348831866, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,395] Trial 73 finished with value: 0.8730606945796818 and parameters: {'C': 0.997603287595345, 'kernel': 'rbf', 'coef0': 0.00042060304494290907, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,426] Trial 74 finished with value: 0.8730606945796818 and parameters: {'C': 0.9414268672416992, 'kernel': 'rbf', 'coef0': 0.15711727001457826, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,456] Trial 75 finished with value: 0.8730606945796818 and parameters: {'C': 0.9662604196604444, 'kernel': 'rbf', 'coef0': 0.05514667128405515, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,486] Trial 76 finished with value: 0.8679974034404415 and parameters: {'C': 0.8772310084289361, 'kernel': 'rbf', 'coef0': 0.11320114357563581, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,502] Trial 77 finished with value: 0.8730606945796818 and parameters: {'C': 0.9176485285603814, 'kernel': 'rbf', 'coef0': 0.020345056415302154, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,517] Trial 78 finished with value: 0.8375527426160337 and parameters: {'C': 0.7611006548908508, 'kernel': 'sigmoid', 'coef0': 0.1954101372540306, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,534] Trial 79 finished with value: 0.8730606945796818 and parameters: {'C': 0.9763790352319573, 'kernel': 'rbf', 'coef0': 0.24566662036005915, 'Class_weight': 'balanced'}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,565] Trial 80 finished with value: 0.8730606945796818 and parameters: {'C': 0.9325496578086572, 'kernel': 'rbf', 'coef0': 0.13884487701359155, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,581] Trial 81 finished with value: 0.8730606945796818 and parameters: {'C': 0.9958792512542094, 'kernel': 'rbf', 'coef0': 0.2686976850866956, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.
[I 2026-06-24 20:13:22,597] Trial 82 finished with value: 0.8730606945796818 and parameters: {'C': 0.967579043077702, 'kernel': 'rbf', 'coef0': 0.3652225826929473, 'Class_weight': None}. Best is trial 48 with value: 0.9012658227848102.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
48,48,0.901266,2026-06-24 20:13:21.763549,2026-06-24 20:13:21.795291,0 days 00:00:00.031742,0.001470,None,0.931381,rbf,COMPLETE
12,12,0.873061,2026-06-24 20:13:20.972415,2026-06-24 20:13:20.987707,0 days 00:00:00.015292,0.985620,None,0.010786,rbf,COMPLETE
16,16,0.873061,2026-06-24 20:13:21.047960,2026-06-24 20:13:21.062949,0 days 00:00:00.014989,0.996775,None,0.379780,rbf,COMPLETE
13,13,0.873061,2026-06-24 20:13:20.987707,2026-06-24 20:13:21.003060,0 days 00:00:00.015353,0.977540,None,0.026491,rbf,COMPLETE
32,32,0.873061,2026-06-24 20:13:21.397461,2026-06-24 20:13:21.427265,0 days 00:00:00.029804,0.929830,None,0.353598,rbf,COMPLETE

In [76]:
top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C']

np.float64(0.0014695513347025013)

In [77]:
model = SVC(
    C=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C'],
    kernel=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_kernel'],
    # degree=degree,
    coef0=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_coef0'],
    # shrinking=shrinking,
    class_weight=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_Class_weight'],
    random_state=random_state,
    cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
)

In [78]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
print(classification_report(y_pred=y_pred, y_true=y_test))
None

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        99
           1       0.50      1.00      0.66        98

    accuracy                           0.50       197
   macro avg       0.25      0.50      0.33       197
weighted avg       0.25      0.50      0.33       197

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

Model overfit due to limited number of samples

## PPP

In [79]:
classification_reports = []
classification_report_keys = []

### Data

In [80]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

### Undersampling

In [81]:
from collections import Counter


X = df.drop(columns='Fraud')
y = df['Fraud']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 968437, 1: 95})
Resampled dataset shape: Counter({0: 95, 1: 95})

### Split Data

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [83]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [84]:
model.fit(X_train, y_train)

SVC()

In [85]:
y_pred = model.predict(X_test)

In [86]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       1.00      0.74      0.85        19
           1       0.79      1.00      0.88        19

    accuracy                           0.87        38
   macro avg       0.90      0.87      0.87        38
weighted avg       0.90      0.87      0.87        38

We see strong performance already without scaling

### Feature Scaling

In [87]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [88]:
model.fit(X_train_scaled, y_train)

SVC()

In [89]:
y_pred = model.predict(X_test_scaled)

In [90]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.93      0.74      0.82        19
           1       0.78      0.95      0.86        19

    accuracy                           0.84        38
   macro avg       0.86      0.84      0.84        38
weighted avg       0.86      0.84      0.84        38

Feature scaling does not affect this dataset

### Parameter Tuning

In [91]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [92]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-24 20:13:25,386] A new study created in memory with name: no-name-0848c74c-3e96-40b7-92e3-038203284678
[I 2026-06-24 20:13:25,413] Trial 0 finished with value: 0.8816666666666666 and parameters: {'C': 0.103351990102654, 'kernel': 'sigmoid', 'coef0': 0.9616089573954022, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8816666666666666.
[I 2026-06-24 20:13:25,427] Trial 1 finished with value: 0.9083333333333332 and parameters: {'C': 0.4194839015078619, 'kernel': 'sigmoid', 'coef0': 0.8293393973371884, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,442] Trial 2 finished with value: 0.8833333333333332 and parameters: {'C': 0.398787895857029, 'kernel': 'rbf', 'coef0': 0.226571131601629, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,457] Trial 3 finished with value: 0.8833333333333332 and parameters: {'C': 0.4252435460851366, 'kernel': 'rbf', 'coef0': 0.3215460979332492, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,473] Trial 4 finished with value: 0.6799999999999999 and parameters: {'C': 0.02369032735931562, 'kernel': 'rbf', 'coef0': 0.24106103135442059, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,488] Trial 5 finished with value: 0.9083333333333332 and parameters: {'C': 0.8142682257237441, 'kernel': 'sigmoid', 'coef0': 0.6699497742988199, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,504] Trial 6 finished with value: 0.8175000000000001 and parameters: {'C': 0.15100238423107495, 'kernel': 'rbf', 'coef0': 0.2500617939114218, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,519] Trial 7 finished with value: 0.9083333333333332 and parameters: {'C': 0.7758009170398121, 'kernel': 'sigmoid', 'coef0': 0.13264867841690953, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,535] Trial 8 finished with value: 0.9083333333333332 and parameters: {'C': 0.3082021555226579, 'kernel': 'sigmoid', 'coef0': 0.1359388475035107, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,557] Trial 9 finished with value: 0.8833333333333332 and parameters: {'C': 0.9297698180443684, 'kernel': 'rbf', 'coef0': 0.422353794239671, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,572] Trial 10 finished with value: 0.9083333333333332 and parameters: {'C': 0.5947553693705449, 'kernel': 'sigmoid', 'coef0': 0.6885665172025267, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,588] Trial 11 finished with value: 0.9083333333333332 and parameters: {'C': 0.6102686720273698, 'kernel': 'sigmoid', 'coef0': 0.7093991259828042, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,604] Trial 12 finished with value: 0.9083333333333332 and parameters: {'C': 0.9661248416177337, 'kernel': 'sigmoid', 'coef0': 0.6912200686886577, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,619] Trial 13 finished with value: 0.9083333333333332 and parameters: {'C': 0.7471504093525239, 'kernel': 'sigmoid', 'coef0': 0.9189415044907955, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,635] Trial 14 finished with value: 0.9083333333333332 and parameters: {'C': 0.2573013331813787, 'kernel': 'sigmoid', 'coef0': 0.8151764884923027, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,651] Trial 15 finished with value: 0.9083333333333332 and parameters: {'C': 0.5642548479381575, 'kernel': 'sigmoid', 'coef0': 0.5770602842333267, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,667] Trial 16 finished with value: 0.9083333333333332 and parameters: {'C': 0.7545107965437673, 'kernel': 'sigmoid', 'coef0': 0.5495271434676741, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,683] Trial 17 finished with value: 0.9083333333333332 and parameters: {'C': 0.8480530169147376, 'kernel': 'sigmoid', 'coef0': 0.8237014421497453, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,708] Trial 18 finished with value: 0.9083333333333332 and parameters: {'C': 0.49356291745991776, 'kernel': 'sigmoid', 'coef0': 0.44543325550533086, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,723] Trial 19 finished with value: 0.9083333333333332 and parameters: {'C': 0.6802479255767825, 'kernel': 'sigmoid', 'coef0': 0.8024529294682892, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,739] Trial 20 finished with value: 0.9083333333333332 and parameters: {'C': 0.27456056981124166, 'kernel': 'sigmoid', 'coef0': 0.6095647947271753, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,763] Trial 21 finished with value: 0.9083333333333332 and parameters: {'C': 0.8636789362959804, 'kernel': 'sigmoid', 'coef0': 0.8814114436949436, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,779] Trial 22 finished with value: 0.9083333333333332 and parameters: {'C': 0.7872417594496609, 'kernel': 'sigmoid', 'coef0': 0.0026881893347480146, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,794] Trial 23 finished with value: 0.9083333333333332 and parameters: {'C': 0.6730893911280412, 'kernel': 'sigmoid', 'coef0': 0.006622129919304137, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,810] Trial 24 finished with value: 0.9083333333333332 and parameters: {'C': 0.5011839570011205, 'kernel': 'sigmoid', 'coef0': 0.7600520414590288, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,827] Trial 25 finished with value: 0.9083333333333332 and parameters: {'C': 0.9881530425950134, 'kernel': 'sigmoid', 'coef0': 0.49833460546725084, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,842] Trial 26 finished with value: 0.8833333333333332 and parameters: {'C': 0.3702931298062895, 'kernel': 'rbf', 'coef0': 0.9832345127729306, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,873] Trial 27 finished with value: 0.9083333333333332 and parameters: {'C': 0.8430429710463202, 'kernel': 'sigmoid', 'coef0': 0.6146316648631005, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,888] Trial 28 finished with value: 0.9083333333333332 and parameters: {'C': 0.6786126644273015, 'kernel': 'sigmoid', 'coef0': 0.3747427625839045, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,904] Trial 29 finished with value: 0.9083333333333332 and parameters: {'C': 0.49139742456986957, 'kernel': 'sigmoid', 'coef0': 0.9070151107201403, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,920] Trial 30 finished with value: 0.9083333333333332 and parameters: {'C': 0.1693469520122295, 'kernel': 'sigmoid', 'coef0': 0.12986713101390346, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,935] Trial 31 finished with value: 0.9083333333333332 and parameters: {'C': 0.32236743555785613, 'kernel': 'sigmoid', 'coef0': 0.15132471914780063, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,957] Trial 32 finished with value: 0.9083333333333332 and parameters: {'C': 0.21436753468950814, 'kernel': 'sigmoid', 'coef0': 0.11413411270617792, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,973] Trial 33 finished with value: 0.9083333333333332 and parameters: {'C': 0.38874769676878423, 'kernel': 'sigmoid', 'coef0': 0.0972999385221677, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:25,988] Trial 34 finished with value: 0.6799999999999999 and parameters: {'C': 0.04924740676689232, 'kernel': 'rbf', 'coef0': 0.2681283456148066, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,003] Trial 35 finished with value: 0.8833333333333332 and parameters: {'C': 0.4434691482182983, 'kernel': 'rbf', 'coef0': 0.19217067784125463, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,018] Trial 36 finished with value: 0.9083333333333332 and parameters: {'C': 0.3299866731299421, 'kernel': 'sigmoid', 'coef0': 0.3359331227297909, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,042] Trial 37 finished with value: 0.8833333333333332 and parameters: {'C': 0.921893872504307, 'kernel': 'rbf', 'coef0': 0.7532157610297343, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,057] Trial 38 finished with value: 0.9083333333333332 and parameters: {'C': 0.5667582517984653, 'kernel': 'sigmoid', 'coef0': 0.6620994031449099, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,074] Trial 39 finished with value: 0.9083333333333332 and parameters: {'C': 0.44403668287462544, 'kernel': 'sigmoid', 'coef0': 0.06258372774039506, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,104] Trial 40 finished with value: 0.8833333333333332 and parameters: {'C': 0.6312086601710075, 'kernel': 'rbf', 'coef0': 0.2856120610368625, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,118] Trial 41 finished with value: 0.9083333333333332 and parameters: {'C': 0.7889984913037376, 'kernel': 'sigmoid', 'coef0': 0.684991772626726, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,140] Trial 42 finished with value: 0.9083333333333332 and parameters: {'C': 0.5418037834432157, 'kernel': 'sigmoid', 'coef0': 0.7437682477494629, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,155] Trial 43 finished with value: 0.9083333333333332 and parameters: {'C': 0.7347708826348402, 'kernel': 'sigmoid', 'coef0': 0.18663147407080607, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,176] Trial 44 finished with value: 0.9083333333333332 and parameters: {'C': 0.9046364696724876, 'kernel': 'sigmoid', 'coef0': 0.8523838355041393, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,192] Trial 45 finished with value: 0.9083333333333332 and parameters: {'C': 0.6161552357418468, 'kernel': 'sigmoid', 'coef0': 0.5013754265756933, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,207] Trial 46 finished with value: 0.9083333333333332 and parameters: {'C': 0.3471036216821085, 'kernel': 'sigmoid', 'coef0': 0.9421089867500178, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,223] Trial 47 finished with value: 0.9083333333333332 and parameters: {'C': 0.2590985005357205, 'kernel': 'sigmoid', 'coef0': 0.7815270805279073, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,254] Trial 48 finished with value: 0.9083333333333332 and parameters: {'C': 0.7144421559097744, 'kernel': 'sigmoid', 'coef0': 0.7074582615826936, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,270] Trial 49 finished with value: 0.9083333333333332 and parameters: {'C': 0.7824023549173142, 'kernel': 'sigmoid', 'coef0': 0.6567124383303636, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,286] Trial 50 finished with value: 0.8949999999999999 and parameters: {'C': 0.11412395647139198, 'kernel': 'sigmoid', 'coef0': 0.559898382195529, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,302] Trial 51 finished with value: 0.9083333333333332 and parameters: {'C': 0.6197626396139391, 'kernel': 'sigmoid', 'coef0': 0.8367789408760952, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,332] Trial 52 finished with value: 0.9083333333333332 and parameters: {'C': 0.535400394814443, 'kernel': 'sigmoid', 'coef0': 0.6263437182468377, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,348] Trial 53 finished with value: 0.9083333333333332 and parameters: {'C': 0.5914119132170763, 'kernel': 'sigmoid', 'coef0': 0.7045215895989152, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,377] Trial 54 finished with value: 0.9083333333333332 and parameters: {'C': 0.41466656596717333, 'kernel': 'sigmoid', 'coef0': 0.05758391653019926, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,402] Trial 55 finished with value: 0.9083333333333332 and parameters: {'C': 0.8421182537143082, 'kernel': 'sigmoid', 'coef0': 0.5198821114402712, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,417] Trial 56 finished with value: 0.9083333333333332 and parameters: {'C': 0.4906300566327051, 'kernel': 'sigmoid', 'coef0': 0.4436977887877005, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,435] Trial 57 finished with value: 0.8833333333333332 and parameters: {'C': 0.7024456668266156, 'kernel': 'rbf', 'coef0': 0.7248420080861389, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,465] Trial 58 finished with value: 0.9083333333333332 and parameters: {'C': 0.2841398615952967, 'kernel': 'sigmoid', 'coef0': 0.865591500563426, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,493] Trial 59 finished with value: 0.9083333333333332 and parameters: {'C': 0.6597191680445178, 'kernel': 'sigmoid', 'coef0': 0.7825459183643793, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,522] Trial 60 finished with value: 0.9083333333333332 and parameters: {'C': 0.8137924969091769, 'kernel': 'sigmoid', 'coef0': 0.8062154989680378, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,538] Trial 61 finished with value: 0.9083333333333332 and parameters: {'C': 0.9715768149200694, 'kernel': 'sigmoid', 'coef0': 0.6046281255009212, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,569] Trial 62 finished with value: 0.9083333333333332 and parameters: {'C': 0.9478478706677979, 'kernel': 'sigmoid', 'coef0': 0.6390391724065779, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,584] Trial 63 finished with value: 0.9083333333333332 and parameters: {'C': 0.878414177077243, 'kernel': 'sigmoid', 'coef0': 0.6632037170532656, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,600] Trial 64 finished with value: 0.9083333333333332 and parameters: {'C': 0.8904999944139269, 'kernel': 'sigmoid', 'coef0': 0.5859288022532563, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,615] Trial 65 finished with value: 0.9083333333333332 and parameters: {'C': 0.9924472878475065, 'kernel': 'sigmoid', 'coef0': 0.2227221505813647, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,631] Trial 66 finished with value: 0.9083333333333332 and parameters: {'C': 0.45586127356621364, 'kernel': 'sigmoid', 'coef0': 0.5359254482731521, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,647] Trial 67 finished with value: 0.8833333333333332 and parameters: {'C': 0.8205059424094426, 'kernel': 'rbf', 'coef0': 0.9083225032488397, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,662] Trial 68 finished with value: 0.9083333333333332 and parameters: {'C': 0.2142592996541115, 'kernel': 'sigmoid', 'coef0': 0.7303492638941563, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,678] Trial 69 finished with value: 0.9083333333333332 and parameters: {'C': 0.7657876882647858, 'kernel': 'sigmoid', 'coef0': 0.7755967427717259, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,695] Trial 70 finished with value: 0.9083333333333332 and parameters: {'C': 0.3975070395591085, 'kernel': 'sigmoid', 'coef0': 0.6905191759621377, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,710] Trial 71 finished with value: 0.9083333333333332 and parameters: {'C': 0.7351000760471494, 'kernel': 'sigmoid', 'coef0': 0.9008237778440762, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,741] Trial 72 finished with value: 0.9083333333333332 and parameters: {'C': 0.6572396325679423, 'kernel': 'sigmoid', 'coef0': 0.9587640923611505, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,757] Trial 73 finished with value: 0.9083333333333332 and parameters: {'C': 0.5835619295035983, 'kernel': 'sigmoid', 'coef0': 0.9292322725062732, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,777] Trial 74 finished with value: 0.9083333333333332 and parameters: {'C': 0.5140930434539266, 'kernel': 'sigmoid', 'coef0': 0.8221105484822605, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,808] Trial 75 finished with value: 0.9083333333333332 and parameters: {'C': 0.3039231591545426, 'kernel': 'sigmoid', 'coef0': 0.07612703190866052, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,826] Trial 76 finished with value: 0.9083333333333332 and parameters: {'C': 0.7020264255659934, 'kernel': 'sigmoid', 'coef0': 0.9731432471845066, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,842] Trial 77 finished with value: 0.8833333333333332 and parameters: {'C': 0.8154016206903197, 'kernel': 'rbf', 'coef0': 0.8789793047957927, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,859] Trial 78 finished with value: 0.9083333333333332 and parameters: {'C': 0.7548005966850123, 'kernel': 'sigmoid', 'coef0': 0.152683125784452, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,890] Trial 79 finished with value: 0.9083333333333332 and parameters: {'C': 0.3586042104730796, 'kernel': 'sigmoid', 'coef0': 0.4131767915336729, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,921] Trial 80 finished with value: 0.9083333333333332 and parameters: {'C': 0.8644795009444362, 'kernel': 'sigmoid', 'coef0': 0.5796867539601257, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.9083333333333332.
[I 2026-06-24 20:13:26,953] Trial 81 finished with value: 0.8949999999999999 and parameters: {'C': 0.21810462324693752, 'kernel': 'sigmoid', 'coef0': 0.8474151287638818, 'Class_weight': None}. Best is trial 1 with value: 0.9083333333333332.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
1,1,0.908333,2026-06-24 20:13:25.413361,2026-06-24 20:13:25.427660,0 days 00:00:00.014299,0.419484,balanced,0.829339,sigmoid,COMPLETE
10,10,0.908333,2026-06-24 20:13:25.557682,2026-06-24 20:13:25.572842,0 days 00:00:00.015160,0.594755,None,0.688567,sigmoid,COMPLETE
7,7,0.908333,2026-06-24 20:13:25.504133,2026-06-24 20:13:25.519724,0 days 00:00:00.015591,0.775801,balanced,0.132649,sigmoid,COMPLETE
5,5,0.908333,2026-06-24 20:13:25.473971,2026-06-24 20:13:25.488930,0 days 00:00:00.014959,0.814268,None,0.669950,sigmoid,COMPLETE
32,32,0.908333,2026-06-24 20:13:25.935856,2026-06-24 20:13:25.957711,0 days 00:00:00.021855,0.214368,balanced,0.114134,sigmoid,COMPLETE

In [93]:
model = SVC(
    C=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C'],
    kernel=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_kernel'],
    # degree=degree,
    coef0=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_coef0'],
    # shrinking=shrinking,
    class_weight=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_Class_weight'],
    random_state=random_state,
    cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
)

In [94]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
print(classification_report(y_pred=y_pred, y_true=y_test))
None

              precision    recall  f1-score   support

           0       1.00      0.74      0.85        19
           1       0.79      1.00      0.88        19

    accuracy                           0.87        38
   macro avg       0.90      0.87      0.87        38
weighted avg       0.90      0.87      0.87        38

The model generalized well