Support vector machines, the kernel trick, and regularization for support vector machines

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
random_state=42

In [3]:
classification_reports = []
classification_report_keys = []

## Data

In [4]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [5]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

## Undersampling

In [6]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 5177, 1: 5177})

## Split Data

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

## Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [8]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [9]:
model.fit(X_train, y_train)

SVC()

In [10]:
y_pred = model.predict(X_test)

In [11]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1036
           1       0.50      0.00      0.00      1035

    accuracy                           0.50      2071
   macro avg       0.50      0.50      0.33      2071
weighted avg       0.50      0.50      0.33      2071

We see poor performance on the positive class, with 0% recall/f1. This could be due to the linear kernal choice or a lack of feature scaling. We can test this assumption during hyper-parameter tuning

## Feature Scaling

In [12]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
model.fit(X_train_scaled, y_train)

SVC()

In [14]:
y_pred = model.predict(X_test_scaled)

In [15]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.89      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

Once feature scaling is applied, recall on positive class jumps from 0% to 88%. This shows that feature scaling was critical for the model. We can attempt to further boost performance with hyperparameter tuning

## Parameter Tuning

In [16]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [23]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-23 17:37:49,722] A new study created in memory with name: no-name-94ca5083-9951-4e3b-b312-c9d613741a0c
[I 2026-06-23 17:37:52,326] Trial 0 finished with value: 0.8401659644644907 and parameters: {'C': 0.676858026763721, 'kernel': 'sigmoid', 'coef0': 0.7460380971840528, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8401659644644907.
[I 2026-06-23 17:37:54,807] Trial 1 finished with value: 0.8493490789788056 and parameters: {'C': 0.10380235686208915, 'kernel': 'rbf', 'coef0': 0.3377403186004688, 'Class_weight': None}. Best is trial 1 with value: 0.8493490789788056.
[I 2026-06-23 17:37:56,881] Trial 2 finished with value: 0.8599733104899098 and parameters: {'C': 0.9450886371817263, 'kernel': 'rbf', 'coef0': 0.8039369407045958, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:37:59,026] Trial 3 finished with value: 0.7998610164157969 and parameters: {'C': 0.6721101170345425, 'kernel': 'sigmoid', 'coef0': 0.022247547208508522, 'Class_weight': None}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:38:00,590] Trial 4 finished with value: 0.8597317645961902 and parameters: {'C': 0.5821638791484655, 'kernel': 'rbf', 'coef0': 0.8302478323235286, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:38:02,165] Trial 5 finished with value: 0.7892283351689655 and parameters: {'C': 0.8850854784963478, 'kernel': 'sigmoid', 'coef0': 0.7224840811765765, 'Class_weight': None}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:38:03,541] Trial 6 finished with value: 0.8097693513516664 and parameters: {'C': 0.40282463901397725, 'kernel': 'sigmoid', 'coef0': 0.6053204442841634, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:38:05,412] Trial 7 finished with value: 0.8592489641789479 and parameters: {'C': 0.18516682172030283, 'kernel': 'rbf', 'coef0': 0.7571015829316616, 'Class_weight': None}. Best is trial 2 with value: 0.8599733104899098.
[I 2026-06-23 17:38:08,013] Trial 8 finished with value: 0.8621469321631906 and parameters: {'C': 0.022532087447934224, 'kernel': 'sigmoid', 'coef0': 0.7839190361110274, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:09,355] Trial 9 finished with value: 0.8078229984324283 and parameters: {'C': 0.3751009173793689, 'kernel': 'sigmoid', 'coef0': 0.10333711603144125, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:13,395] Trial 10 finished with value: 0.3821943672313421 and parameters: {'C': 0.0034581361687067713, 'kernel': 'sigmoid', 'coef0': 0.9814946111645184, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:14,821] Trial 11 finished with value: 0.8599733104899098 and parameters: {'C': 0.9603461983669702, 'kernel': 'rbf', 'coef0': 0.991726855512382, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:16,681] Trial 12 finished with value: 0.8599733104899098 and parameters: {'C': 0.8004502035668397, 'kernel': 'rbf', 'coef0': 0.44816917746872803, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:18,390] Trial 13 finished with value: 0.8597317645961902 and parameters: {'C': 0.28913414158817796, 'kernel': 'rbf', 'coef0': 0.5691114705136318, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:19,842] Trial 14 finished with value: 0.83485137206226 and parameters: {'C': 0.5349488168969933, 'kernel': 'sigmoid', 'coef0': 0.8372743804930706, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:21,286] Trial 15 finished with value: 0.8599733104899098 and parameters: {'C': 0.7814168191612714, 'kernel': 'rbf', 'coef0': 0.36170460725552456, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:22,949] Trial 16 finished with value: 0.8481489251353415 and parameters: {'C': 0.24242146908372622, 'kernel': 'sigmoid', 'coef0': 0.6261335603680069, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:24,426] Trial 17 finished with value: 0.8597317645961902 and parameters: {'C': 0.45814641865270106, 'kernel': 'rbf', 'coef0': 0.8729914284796, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:26,080] Trial 18 finished with value: 0.8621469321631906 and parameters: {'C': 0.041111421982599206, 'kernel': 'sigmoid', 'coef0': 0.45170738695216606, 'Class_weight': None}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:27,272] Trial 19 finished with value: 0.8336488872572158 and parameters: {'C': 0.15495283003791535, 'kernel': 'sigmoid', 'coef0': 0.27087144831404353, 'Class_weight': None}. Best is trial 8 with value: 0.8621469321631906.
[I 2026-06-23 17:38:30,603] Trial 20 finished with value: 0.898618905263894 and parameters: {'C': 0.0021309669930490716, 'kernel': 'sigmoid', 'coef0': 0.21359328071893918, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:32,289] Trial 21 finished with value: 0.8619056776396683 and parameters: {'C': 0.03305658216050173, 'kernel': 'sigmoid', 'coef0': 0.2027138194236135, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:33,693] Trial 22 finished with value: 0.8599738932303047 and parameters: {'C': 0.08583108733980772, 'kernel': 'sigmoid', 'coef0': 0.46454185677458154, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:34,912] Trial 23 finished with value: 0.7957556103331527 and parameters: {'C': 0.29266742339354995, 'kernel': 'sigmoid', 'coef0': 0.17690022909734388, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:36,213] Trial 24 finished with value: 0.8582833633444636 and parameters: {'C': 0.12235060471713302, 'kernel': 'sigmoid', 'coef0': 0.3811997697420979, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:38,347] Trial 25 finished with value: 0.8621469321631906 and parameters: {'C': 0.019768306756159173, 'kernel': 'sigmoid', 'coef0': 0.5148014435927681, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:39,599] Trial 26 finished with value: 0.8292966906172969 and parameters: {'C': 0.20213350786042852, 'kernel': 'sigmoid', 'coef0': 0.2703785937700705, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:41,188] Trial 27 finished with value: 0.8597323473365851 and parameters: {'C': 0.08441001653571592, 'kernel': 'sigmoid', 'coef0': 0.09588813300574195, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:42,597] Trial 28 finished with value: 0.8293188347523064 and parameters: {'C': 0.31433440053791384, 'kernel': 'sigmoid', 'coef0': 0.6628832022661965, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:44,305] Trial 29 finished with value: 0.8698691165072873 and parameters: {'C': 0.2191714978845163, 'kernel': 'sigmoid', 'coef0': 0.9056226066816384, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:46,059] Trial 30 finished with value: 0.8730086303852497 and parameters: {'C': 0.19650378076099326, 'kernel': 'sigmoid', 'coef0': 0.9136439876320241, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:47,948] Trial 31 finished with value: 0.8643129782113366 and parameters: {'C': 0.20853248708227315, 'kernel': 'sigmoid', 'coef0': 0.939707917541818, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:49,619] Trial 32 finished with value: 0.8715576068017461 and parameters: {'C': 0.22415600355949597, 'kernel': 'sigmoid', 'coef0': 0.9106942369868757, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:51,214] Trial 33 finished with value: 0.8640763856109741 and parameters: {'C': 0.36807130164236634, 'kernel': 'sigmoid', 'coef0': 0.9352440470558724, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:52,829] Trial 34 finished with value: 0.8645612256195987 and parameters: {'C': 0.24271320736719781, 'kernel': 'sigmoid', 'coef0': 0.9093320411074909, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:54,300] Trial 35 finished with value: 0.8597323473365851 and parameters: {'C': 0.1453780977781225, 'kernel': 'sigmoid', 'coef0': 0.7023588351254731, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:55,753] Trial 36 finished with value: 0.8481497992459339 and parameters: {'C': 0.449142477121807, 'kernel': 'sigmoid', 'coef0': 0.8533715662473342, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:57,234] Trial 37 finished with value: 0.8399322855661031 and parameters: {'C': 0.32748422754308726, 'kernel': 'sigmoid', 'coef0': 0.8884166673165788, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:38:58,817] Trial 38 finished with value: 0.8582813237530813 and parameters: {'C': 0.24409532986662827, 'kernel': 'sigmoid', 'coef0': 0.7976787370810006, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:00,042] Trial 39 finished with value: 0.7974414782958339 and parameters: {'C': 0.6100799813277189, 'kernel': 'sigmoid', 'coef0': 0.009209937324601819, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:01,985] Trial 40 finished with value: 0.8626306066910253 and parameters: {'C': 0.07144300220019603, 'kernel': 'sigmoid', 'coef0': 0.7149530648832041, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:03,574] Trial 41 finished with value: 0.8638412498615992 and parameters: {'C': 0.2627256794895755, 'kernel': 'sigmoid', 'coef0': 0.9272062658465247, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:05,269] Trial 42 finished with value: 0.8669699830422545 and parameters: {'C': 0.17032769342967102, 'kernel': 'sigmoid', 'coef0': 0.8985335596784523, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:07,034] Trial 43 finished with value: 0.8804968444607612 and parameters: {'C': 0.1908276020442897, 'kernel': 'sigmoid', 'coef0': 0.9967981637455542, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:08,815] Trial 44 finished with value: 0.8539300012237548 and parameters: {'C': 0.3531994560512267, 'kernel': 'sigmoid', 'coef0': 0.9946983824469489, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:10,423] Trial 45 finished with value: 0.8254421542746921 and parameters: {'C': 0.4185998327497432, 'kernel': 'sigmoid', 'coef0': 0.7584753100902393, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:11,842] Trial 46 finished with value: 0.8602151477538271 and parameters: {'C': 0.12669764085518564, 'kernel': 'sigmoid', 'coef0': 0.8194202180103765, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:13,647] Trial 47 finished with value: 0.8592489641789479 and parameters: {'C': 0.18795230787239592, 'kernel': 'rbf', 'coef0': 0.9415860462619507, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:15,382] Trial 48 finished with value: 0.8452471693385313 and parameters: {'C': 0.5048219309025614, 'kernel': 'sigmoid', 'coef0': 0.9932474767203396, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:16,949] Trial 49 finished with value: 0.8592489641789479 and parameters: {'C': 0.21713152644936856, 'kernel': 'rbf', 'coef0': 0.8533828018568158, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:19,118] Trial 50 finished with value: 0.8616644231161459 and parameters: {'C': 0.06321900241165707, 'kernel': 'sigmoid', 'coef0': 0.9592593803758888, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:20,724] Trial 51 finished with value: 0.8669699830422545 and parameters: {'C': 0.16876367659986477, 'kernel': 'sigmoid', 'coef0': 0.8969772636045291, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:22,380] Trial 52 finished with value: 0.8669702744124519 and parameters: {'C': 0.11494937900285801, 'kernel': 'sigmoid', 'coef0': 0.7959769601489992, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:24,129] Trial 53 finished with value: 0.8655294487858605 and parameters: {'C': 0.10860167317210079, 'kernel': 'sigmoid', 'coef0': 0.8168767344723474, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:25,651] Trial 54 finished with value: 0.8252125545590694 and parameters: {'C': 0.283860501276725, 'kernel': 'sigmoid', 'coef0': 0.7554042473989244, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:27,307] Trial 55 finished with value: 0.860456110907152 and parameters: {'C': 0.11030333638184259, 'kernel': 'sigmoid', 'coef0': 0.5647522888300042, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:29,434] Trial 56 finished with value: 0.8616644231161459 and parameters: {'C': 0.06091317179158892, 'kernel': 'sigmoid', 'coef0': 0.9668586944783264, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:31,577] Trial 57 finished with value: 0.7199346748017226 and parameters: {'C': 0.025495801128659016, 'kernel': 'rbf', 'coef0': 0.8466436933942859, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:33,262] Trial 58 finished with value: 0.872042738180568 and parameters: {'C': 0.14360991046449123, 'kernel': 'sigmoid', 'coef0': 0.7765612653755765, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:34,608] Trial 59 finished with value: 0.8037280816768938 and parameters: {'C': 0.9988950874707125, 'kernel': 'sigmoid', 'coef0': 0.8722467441979651, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:36,091] Trial 60 finished with value: 0.8522432591504809 and parameters: {'C': 0.22087825714694698, 'kernel': 'sigmoid', 'coef0': 0.669595375781108, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:37,778] Trial 61 finished with value: 0.8698688251370899 and parameters: {'C': 0.15160460577224036, 'kernel': 'sigmoid', 'coef0': 0.7871870166157351, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:39,233] Trial 62 finished with value: 0.8500798354341125 and parameters: {'C': 0.16184224876070324, 'kernel': 'sigmoid', 'coef0': 0.08373011659545626, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:40,966] Trial 63 finished with value: 0.8689003106006306 and parameters: {'C': 0.14441710556664383, 'kernel': 'sigmoid', 'coef0': 0.7692382690926929, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:44,448] Trial 64 finished with value: 0.8570735942844824 and parameters: {'C': 0.003905633298331851, 'kernel': 'sigmoid', 'coef0': 0.9130643028618131, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:45,745] Trial 65 finished with value: 0.8049273614097656 and parameters: {'C': 0.31246508629445896, 'kernel': 'sigmoid', 'coef0': 0.3071563900635509, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:47,292] Trial 66 finished with value: 0.8493549063827555 and parameters: {'C': 0.2738041934170697, 'kernel': 'sigmoid', 'coef0': 0.9608079026581846, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:48,866] Trial 67 finished with value: 0.8592489641789479 and parameters: {'C': 0.20439544193031062, 'kernel': 'rbf', 'coef0': 0.736837851960866, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:50,038] Trial 68 finished with value: 0.8005862368373512 and parameters: {'C': 0.8657760338221486, 'kernel': 'sigmoid', 'coef0': 0.19707999036635085, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:51,620] Trial 69 finished with value: 0.8396977325571232 and parameters: {'C': 0.23571796752301044, 'kernel': 'sigmoid', 'coef0': 0.6417180585290644, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:53,117] Trial 70 finished with value: 0.8430717994440657 and parameters: {'C': 0.34156641321794434, 'kernel': 'sigmoid', 'coef0': 0.8758277474882461, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:54,716] Trial 71 finished with value: 0.844523697138162 and parameters: {'C': 0.14429707915201015, 'kernel': 'sigmoid', 'coef0': 0.40994720597147344, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:56,429] Trial 72 finished with value: 0.8604520317243871 and parameters: {'C': 0.1864309772955488, 'kernel': 'sigmoid', 'coef0': 0.7801941236014103, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:57,739] Trial 73 finished with value: 0.8350937920665723 and parameters: {'C': 0.7161061214051414, 'kernel': 'sigmoid', 'coef0': 0.5961952392167991, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:39:59,518] Trial 74 finished with value: 0.8657707033093827 and parameters: {'C': 0.09006326673465373, 'kernel': 'sigmoid', 'coef0': 0.844382887186701, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:01,096] Trial 75 finished with value: 0.8747058617856333 and parameters: {'C': 0.13976114427256503, 'kernel': 'sigmoid', 'coef0': 0.7795486664976237, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:02,631] Trial 76 finished with value: 0.8621469321631906 and parameters: {'C': 0.05738297339789378, 'kernel': 'sigmoid', 'coef0': 0.7022422281219348, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:04,023] Trial 77 finished with value: 0.8442815685040472 and parameters: {'C': 0.1845568071572525, 'kernel': 'sigmoid', 'coef0': 0.5096278929497284, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:05,615] Trial 78 finished with value: 0.8582813237530811 and parameters: {'C': 0.2557123674809526, 'kernel': 'sigmoid', 'coef0': 0.9234856302524395, 'Class_weight': 'balanced'}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:06,986] Trial 79 finished with value: 0.8527359661544379 and parameters: {'C': 0.13062085334341622, 'kernel': 'sigmoid', 'coef0': 0.053521918434300986, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.
[I 2026-06-23 17:40:08,814] Trial 80 finished with value: 0.8597317645961902 and parameters: {'C': 0.29390392619429795, 'kernel': 'rbf', 'coef0': 0.9629715995944101, 'Class_weight': None}. Best is trial 20 with value: 0.898618905263894.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
20,20,0.898619,2026-06-23 17:38:27.273556,2026-06-23 17:38:30.603196,0 days 00:00:03.329640,0.002131,None,0.213593,sigmoid,COMPLETE
43,43,0.880497,2026-06-23 17:39:05.270358,2026-06-23 17:39:07.034440,0 days 00:00:01.764082,0.190828,None,0.996798,sigmoid,COMPLETE
75,75,0.874706,2026-06-23 17:39:59.519510,2026-06-23 17:40:01.096558,0 days 00:00:01.577048,0.139761,balanced,0.779549,sigmoid,COMPLETE
30,30,0.873009,2026-06-23 17:38:44.306279,2026-06-23 17:38:46.059585,0 days 00:00:01.753306,0.196504,None,0.913644,sigmoid,COMPLETE
96,96,0.872526,2026-06-23 17:40:37.711138,2026-06-23 17:40:39.371542,0 days 00:00:01.660404,0.101529,None,0.809855,sigmoid,COMPLETE