Support vector machines, the kernel trick, and regularization for support vector machines

In [73]:
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm 
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import average_precision_score

In [74]:
random_state=42

## IBM

In [75]:
classification_reports = []
classification_report_keys = []

### Data

In [76]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ibm_hi_small_trans_cleaned.csv')
df

,Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Amount Paid,Is Laundering,Amount_Received_USD,Amount_Paid_USD,...,Payment Currency_Yuan,Payment Format_ACH,Payment Format_Bitcoin,Payment Format_Cash,Payment Format_Cheque,Payment Format_Credit Card,Payment Format_Reinvestment,Payment Format_Wire,Account_Same,Bank_Same
0,2022/09/01 00:20,10,8000EBD30,10,8000EBD30,3697.340000,3697.340000,0,3697.340000,3697.340000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
1,2022/09/01 00:20,3208,8000F4580,1,8000F5340,0.010000,0.010000,0,0.010000,0.010000,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0,0
2,2022/09/01 00:00,3209,8000F4670,3209,8000F4670,14675.570000,14675.570000,0,14675.570000,14675.570000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
3,2022/09/01 00:02,12,8000F5030,12,8000F5030,2806.970000,2806.970000,0,2806.970000,2806.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
4,2022/09/01 00:06,10,8000F5200,10,8000F5200,36682.970000,36682.970000,0,36682.970000,36682.970000,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078340,2022/09/10 23:57,54219,8148A6631,256398,8148A8711,0.154978,0.154978,0,3107.386389,3107.386389,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078341,2022/09/10 23:35,15,8148A8671,256398,8148A8711,0.108128,0.108128,0,2168.020464,2168.020464,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078342,2022/09/10 23:52,154365,8148A6771,256398,8148A8711,0.004988,0.004988,0,100.011894,100.011894,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0
5078343,2022/09/10 23:46,256398,8148A6311,256398,8148A8711,0.038417,0.038417,0,770.280058,770.280058,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,1
5078344,2022/09/10 23:37,154518,8148A6091,256398,8148A8711,0.281983,0.281983,0,5653.900141,5653.900141,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0,0

In [77]:
df.drop(columns=['Timestamp', 'From Bank', 'To Bank', 'Account', 'Account.1'], inplace=True)

### Undersampling

In [78]:
from collections import Counter


X = df.drop(columns='Is Laundering')
y = df['Is Laundering']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 5073168, 1: 5177})
Resampled dataset shape: Counter({0: 5177, 1: 5177})

### Split Data

In [79]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [80]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [81]:
model.fit(X_train, y_train)

SVC()

In [82]:
y_pred = model.predict(X_test)

In [83]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.50      1.00      0.67      1036
           1       0.50      0.00      0.00      1035

    accuracy                           0.50      2071
   macro avg       0.50      0.50      0.33      2071
weighted avg       0.50      0.50      0.33      2071

In [84]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.49975880400376027

0% positive class recall

### Feature Scaling

In [85]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [86]:
model.fit(X_train_scaled, y_train)

SVC()

In [87]:
y_pred = model.predict(X_test_scaled)

In [88]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.88      0.89      0.89      1036
           1       0.89      0.88      0.89      1035

    accuracy                           0.89      2071
   macro avg       0.89      0.89      0.89      2071
weighted avg       0.89      0.89      0.89      2071

In [89]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8439974899956337

Once feature scaling is applied, recall on positive class jumps from 0% to 88%. This shows that feature scaling was critical for the model. We can attempt to further boost performance with hyperparameter tuning

### Parameter Tuning

In [90]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [91]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-25 21:15:27,328] A new study created in memory with name: no-name-e7a78330-f942-49e5-8842-05a8a6a93be0
[I 2026-06-25 21:15:30,126] Trial 0 finished with value: 0.8594908014428653 and parameters: {'C': 0.17210731998578274, 'kernel': 'sigmoid', 'coef0': 0.8204294559091749, 'Class_weight': None}. Best is trial 0 with value: 0.8594908014428653.
[I 2026-06-25 21:15:32,526] Trial 1 finished with value: 0.8599733104899098 and parameters: {'C': 0.8821981003262893, 'kernel': 'rbf', 'coef0': 0.7943954921235733, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:34,994] Trial 2 finished with value: 0.8225456431414369 and parameters: {'C': 0.6055241410208279, 'kernel': 'sigmoid', 'coef0': 0.642230938016501, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:37,692] Trial 3 finished with value: 0.8590152852805604 and parameters: {'C': 0.1956191071461363, 'kernel': 'sigmoid', 'coef0': 0.8286894517121158, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:39,159] Trial 4 finished with value: 0.852484222303806 and parameters: {'C': 0.24421382430876304, 'kernel': 'sigmoid', 'coef0': 0.7809213208033198, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:40,939] Trial 5 finished with value: 0.85683350524175 and parameters: {'C': 0.1602757543801789, 'kernel': 'rbf', 'coef0': 0.24676782082330706, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:42,082] Trial 6 finished with value: 0.8039632174262689 and parameters: {'C': 0.589503320640843, 'kernel': 'sigmoid', 'coef0': 0.303822895068403, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:43,514] Trial 7 finished with value: 0.8599733104899098 and parameters: {'C': 0.7467897771299549, 'kernel': 'rbf', 'coef0': 0.32578984782643927, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:44,868] Trial 8 finished with value: 0.8597317645961902 and parameters: {'C': 0.6671788893446347, 'kernel': 'rbf', 'coef0': 0.9401497645836803, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:46,342] Trial 9 finished with value: 0.8597317645961902 and parameters: {'C': 0.5396814345652775, 'kernel': 'rbf', 'coef0': 0.10812862175230564, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:47,625] Trial 10 finished with value: 0.8599733104899098 and parameters: {'C': 0.9912802420966743, 'kernel': 'rbf', 'coef0': 0.5206673143738496, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:48,918] Trial 11 finished with value: 0.8599733104899098 and parameters: {'C': 0.8948254401493019, 'kernel': 'rbf', 'coef0': 0.407389891310618, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:50,288] Trial 12 finished with value: 0.8599733104899098 and parameters: {'C': 0.8123770056050246, 'kernel': 'rbf', 'coef0': 0.5591054374249108, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:51,614] Trial 13 finished with value: 0.8599733104899098 and parameters: {'C': 0.8057010652155951, 'kernel': 'rbf', 'coef0': 0.12421069139149471, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:53,091] Trial 14 finished with value: 0.8597317645961902 and parameters: {'C': 0.4243103832429254, 'kernel': 'rbf', 'coef0': 0.37761701336986636, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:54,472] Trial 15 finished with value: 0.8599733104899098 and parameters: {'C': 0.7436685760882272, 'kernel': 'rbf', 'coef0': 0.6871889203602596, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:55,765] Trial 16 finished with value: 0.8599733104899098 and parameters: {'C': 0.9687346974184023, 'kernel': 'rbf', 'coef0': 0.015520469029921657, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:56,942] Trial 17 finished with value: 0.8597317645961902 and parameters: {'C': 0.7281794239907697, 'kernel': 'rbf', 'coef0': 0.9487346214428816, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:15:58,287] Trial 18 finished with value: 0.8597317645961902 and parameters: {'C': 0.44172187002726804, 'kernel': 'rbf', 'coef0': 0.43809349373003775, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:00,076] Trial 19 finished with value: 0.8182039358286277 and parameters: {'C': 0.042500964352487014, 'kernel': 'rbf', 'coef0': 0.6368611298806729, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:01,365] Trial 20 finished with value: 0.8599733104899098 and parameters: {'C': 0.8850130462513324, 'kernel': 'rbf', 'coef0': 0.3012118902218362, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:02,594] Trial 21 finished with value: 0.8599733104899098 and parameters: {'C': 0.9728995686015314, 'kernel': 'rbf', 'coef0': 0.5097942027721798, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:03,896] Trial 22 finished with value: 0.8599733104899098 and parameters: {'C': 0.8806030125993838, 'kernel': 'rbf', 'coef0': 0.5570912807120589, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:05,218] Trial 23 finished with value: 0.8599733104899098 and parameters: {'C': 0.975425597954248, 'kernel': 'rbf', 'coef0': 0.21193488214260459, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:06,554] Trial 24 finished with value: 0.8599733104899098 and parameters: {'C': 0.7983252766558079, 'kernel': 'rbf', 'coef0': 0.999048400234464, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:07,694] Trial 25 finished with value: 0.8597317645961902 and parameters: {'C': 0.7124608717959606, 'kernel': 'rbf', 'coef0': 0.7245283285219596, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:08,720] Trial 26 finished with value: 0.7964648053938451 and parameters: {'C': 0.8942610191815964, 'kernel': 'sigmoid', 'coef0': 0.486375401974931, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:09,785] Trial 27 finished with value: 0.8599733104899098 and parameters: {'C': 0.9978091923094695, 'kernel': 'rbf', 'coef0': 0.3462463063363914, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:10,923] Trial 28 finished with value: 0.8597317645961902 and parameters: {'C': 0.6550289104971732, 'kernel': 'rbf', 'coef0': 0.4567964125561812, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:12,041] Trial 29 finished with value: 0.8155483878486974 and parameters: {'C': 0.8314700246271394, 'kernel': 'sigmoid', 'coef0': 0.8209889519188068, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:13,234] Trial 30 finished with value: 0.8597317645961902 and parameters: {'C': 0.3304380644429201, 'kernel': 'rbf', 'coef0': 0.591036626992038, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:14,330] Trial 31 finished with value: 0.8599733104899098 and parameters: {'C': 0.9078860686054483, 'kernel': 'rbf', 'coef0': 0.3582830949868979, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:15,447] Trial 32 finished with value: 0.8599733104899098 and parameters: {'C': 0.9219587455903314, 'kernel': 'rbf', 'coef0': 0.42046025231397655, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:16,575] Trial 33 finished with value: 0.8599733104899098 and parameters: {'C': 0.7660161156580996, 'kernel': 'rbf', 'coef0': 0.20956743521945656, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:17,814] Trial 34 finished with value: 0.8058961673164223 and parameters: {'C': 0.8584778597782646, 'kernel': 'sigmoid', 'coef0': 0.8951158846392826, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:18,940] Trial 35 finished with value: 0.8599733104899098 and parameters: {'C': 0.9498035137896801, 'kernel': 'rbf', 'coef0': 0.7490764653612022, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:20,002] Trial 36 finished with value: 0.8278477066251755 and parameters: {'C': 0.6697404623274054, 'kernel': 'sigmoid', 'coef0': 0.5284063338687043, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:21,043] Trial 37 finished with value: 0.8599733104899098 and parameters: {'C': 0.8437708434282335, 'kernel': 'rbf', 'coef0': 0.6311983932488082, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:21,978] Trial 38 finished with value: 0.81506850113343 and parameters: {'C': 0.6020322704924066, 'kernel': 'sigmoid', 'coef0': 0.4096149568493798, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:23,135] Trial 39 finished with value: 0.8597317645961902 and parameters: {'C': 0.5306284380965622, 'kernel': 'rbf', 'coef0': 0.30355789099667374, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:24,250] Trial 40 finished with value: 0.8599733104899098 and parameters: {'C': 0.7741930192277083, 'kernel': 'rbf', 'coef0': 0.2644255095599631, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:25,366] Trial 41 finished with value: 0.8599733104899098 and parameters: {'C': 0.8302185240719959, 'kernel': 'rbf', 'coef0': 0.548111226914734, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:26,523] Trial 42 finished with value: 0.8599733104899098 and parameters: {'C': 0.9305593671257341, 'kernel': 'rbf', 'coef0': 0.6886049891764306, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:27,633] Trial 43 finished with value: 0.8597317645961902 and parameters: {'C': 0.6987042128638983, 'kernel': 'rbf', 'coef0': 0.4769214806510869, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:28,839] Trial 44 finished with value: 0.8599733104899098 and parameters: {'C': 0.7962559319244147, 'kernel': 'rbf', 'coef0': 0.5975266413726018, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:29,943] Trial 45 finished with value: 0.8599733104899098 and parameters: {'C': 0.8634530989840551, 'kernel': 'rbf', 'coef0': 0.13871825416791173, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:31,042] Trial 46 finished with value: 0.8599733104899098 and parameters: {'C': 0.9394956120052164, 'kernel': 'rbf', 'coef0': 0.39361561134006856, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:32,246] Trial 47 finished with value: 0.8597317645961902 and parameters: {'C': 0.6280646498484193, 'kernel': 'rbf', 'coef0': 0.8843907394888884, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:33,416] Trial 48 finished with value: 0.8599733104899098 and parameters: {'C': 0.768230146904153, 'kernel': 'rbf', 'coef0': 0.7775553381618825, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:34,573] Trial 49 finished with value: 0.8597317645961902 and parameters: {'C': 0.5612938869504593, 'kernel': 'rbf', 'coef0': 0.3407831910127661, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:35,727] Trial 50 finished with value: 0.8314857549110448 and parameters: {'C': 0.9958889088520269, 'kernel': 'sigmoid', 'coef0': 0.5875871251735192, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:36,841] Trial 51 finished with value: 0.8599733104899098 and parameters: {'C': 0.8009483923687324, 'kernel': 'rbf', 'coef0': 0.144030322239667, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:37,951] Trial 52 finished with value: 0.8599733104899098 and parameters: {'C': 0.824242708127287, 'kernel': 'rbf', 'coef0': 0.0004165884673300174, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:39,102] Trial 53 finished with value: 0.8599733104899098 and parameters: {'C': 0.7433714073241497, 'kernel': 'rbf', 'coef0': 0.0675489579827227, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:40,194] Trial 54 finished with value: 0.8599733104899098 and parameters: {'C': 0.8943466187941496, 'kernel': 'rbf', 'coef0': 0.5095921022057309, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:41,891] Trial 55 finished with value: 0.7199346748017226 and parameters: {'C': 0.02620242540149309, 'kernel': 'rbf', 'coef0': 0.19886905058884702, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:43,313] Trial 56 finished with value: 0.8597317645961902 and parameters: {'C': 0.4802806501673544, 'kernel': 'rbf', 'coef0': 0.25576705517302867, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:44,506] Trial 57 finished with value: 0.8597317645961902 and parameters: {'C': 0.6957146380186575, 'kernel': 'rbf', 'coef0': 0.4464946190510774, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:45,959] Trial 58 finished with value: 0.8599733104899098 and parameters: {'C': 0.954718447692939, 'kernel': 'rbf', 'coef0': 0.6865156958432959, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:47,244] Trial 59 finished with value: 0.8597317645961902 and parameters: {'C': 0.34472382181452926, 'kernel': 'rbf', 'coef0': 0.04498017939594351, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:48,335] Trial 60 finished with value: 0.8599733104899098 and parameters: {'C': 0.8798240144384278, 'kernel': 'rbf', 'coef0': 0.3750541736771737, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:49,521] Trial 61 finished with value: 0.8597317645961902 and parameters: {'C': 0.7383237879738388, 'kernel': 'rbf', 'coef0': 0.686397922175453, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:50,681] Trial 62 finished with value: 0.8599733104899098 and parameters: {'C': 0.813279194320576, 'kernel': 'rbf', 'coef0': 0.8752382370067688, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:52,102] Trial 63 finished with value: 0.8515227006520865 and parameters: {'C': 0.13523053994510648, 'kernel': 'rbf', 'coef0': 0.6391246634341803, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:53,384] Trial 64 finished with value: 0.8599733104899098 and parameters: {'C': 0.855020297727768, 'kernel': 'rbf', 'coef0': 0.7828764486268084, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:54,773] Trial 65 finished with value: 0.8599733104899098 and parameters: {'C': 0.9185014135651741, 'kernel': 'rbf', 'coef0': 0.5539538880060977, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:55,940] Trial 66 finished with value: 0.8054063740144404 and parameters: {'C': 0.6578285995146198, 'kernel': 'sigmoid', 'coef0': 0.7215919607456501, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:57,311] Trial 67 finished with value: 0.8599733104899098 and parameters: {'C': 0.7783901584138101, 'kernel': 'rbf', 'coef0': 0.8401032610010074, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:16:58,732] Trial 68 finished with value: 0.8599733104899098 and parameters: {'C': 0.9938892131651836, 'kernel': 'rbf', 'coef0': 0.46578162481143365, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:00,200] Trial 69 finished with value: 0.8597317645961902 and parameters: {'C': 0.7339079563648114, 'kernel': 'rbf', 'coef0': 0.33127812109867494, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:01,439] Trial 70 finished with value: 0.8599733104899098 and parameters: {'C': 0.9046947907110314, 'kernel': 'rbf', 'coef0': 0.6162649040111498, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:02,864] Trial 71 finished with value: 0.8599733104899098 and parameters: {'C': 0.9702650438407657, 'kernel': 'rbf', 'coef0': 0.011736229741573012, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:04,140] Trial 72 finished with value: 0.8599733104899098 and parameters: {'C': 0.949087925353679, 'kernel': 'rbf', 'coef0': 0.13152614142014446, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:05,452] Trial 73 finished with value: 0.8599733104899098 and parameters: {'C': 0.8730685139159668, 'kernel': 'rbf', 'coef0': 0.08653989970665585, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:06,682] Trial 74 finished with value: 0.8599733104899098 and parameters: {'C': 0.8433802458932769, 'kernel': 'rbf', 'coef0': 0.42510601255020203, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:07,804] Trial 75 finished with value: 0.7938197467410243 and parameters: {'C': 0.9782759649124623, 'kernel': 'sigmoid', 'coef0': 0.1604337317889402, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:09,225] Trial 76 finished with value: 0.8599733104899098 and parameters: {'C': 0.9170676526414095, 'kernel': 'rbf', 'coef0': 0.17874310010829964, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:10,726] Trial 77 finished with value: 0.8597317645961902 and parameters: {'C': 0.6327092782670275, 'kernel': 'rbf', 'coef0': 0.03670087394759708, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:11,929] Trial 78 finished with value: 0.8599733104899098 and parameters: {'C': 0.8814810859452157, 'kernel': 'rbf', 'coef0': 0.5174035611550797, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:13,299] Trial 79 finished with value: 0.8599733104899098 and parameters: {'C': 0.7969501023123786, 'kernel': 'rbf', 'coef0': 0.2836086794578965, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:14,640] Trial 80 finished with value: 0.8597317645961902 and parameters: {'C': 0.7114593072355593, 'kernel': 'rbf', 'coef0': 0.5720062760423418, 'Class_weight': None}. Best is trial 1 with value: 0.8599733104899098.
[I 2026-06-25 21:17:15,908] Trial 81 finished with value: 0.8599733104899098 and parameters: {'C': 0.9364152419207171, 'kernel': 'rbf', 'coef0': 0.2998007539262383, 'Class_weight': 'balanced'}. Best is trial 1 with value: 0.8599733104899098.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
1,1,0.859973,2026-06-25 21:15:30.127529,2026-06-25 21:15:32.526700,0 days 00:00:02.399171,0.882198,None,0.794395,rbf,COMPLETE
10,10,0.859973,2026-06-25 21:15:46.344488,2026-06-25 21:15:47.625120,0 days 00:00:01.280632,0.991280,None,0.520667,rbf,COMPLETE
11,11,0.859973,2026-06-25 21:15:47.627122,2026-06-25 21:15:48.918295,0 days 00:00:01.291173,0.894825,balanced,0.407390,rbf,COMPLETE
7,7,0.859973,2026-06-25 21:15:42.082426,2026-06-25 21:15:43.514958,0 days 00:00:01.432532,0.746790,balanced,0.325790,rbf,COMPLETE
32,32,0.859973,2026-06-25 21:16:14.330727,2026-06-25 21:16:15.447719,0 days 00:00:01.116992,0.921959,balanced,0.420460,rbf,COMPLETE

In [92]:
model = SVC(
    C=0.119487,
    kernel='sigmoid',
    # degree=degree,
    coef0=0.745768,
    # shrinking=shrinking,
    class_weight=None,
    random_state=random_state,
    cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
)
model.fit(X_train_scaled, y_train)

SVC(C=0.119487, cache_size=1000, coef0=0.745768, kernel='sigmoid',
    random_state=42)

In [93]:
y_pred = model.predict(X_test_scaled)

In [94]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.89      0.86      0.87      1036
           1       0.86      0.89      0.88      1035

    accuracy                           0.87      2071
   macro avg       0.87      0.87      0.87      2071
weighted avg       0.87      0.87      0.87      2071

In [95]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.8226748630818774

## Credit Card

In [96]:
classification_reports = []
classification_report_keys = []

### Data

In [97]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling

In [98]:
from collections import Counter


X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 492, 1: 492})

### Split Data

In [99]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [100]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [101]:
model.fit(X_train, y_train)

SVC()

In [102]:
y_pred = model.predict(X_test)

In [103]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.54      0.49      0.52        99
           1       0.53      0.57      0.55        98

    accuracy                           0.53       197
   macro avg       0.53      0.53      0.53       197
weighted avg       0.53      0.53      0.53       197

In [104]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.5150847619959774

We see poor performance with macro avg f1 of 0.53 and consistent performance across positive and negative class. This could be due to the linear kernal choice or a lack of feature scaling. We can test this assumption during hyper-parameter tuning

### Feature Scaling

In [105]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [106]:
model.fit(X_train_scaled, y_train)

SVC()

In [107]:
y_pred = model.predict(X_test_scaled)

In [108]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.94      0.99      0.97        99
           1       0.99      0.94      0.96        98

    accuracy                           0.96       197
   macro avg       0.97      0.96      0.96       197
weighted avg       0.97      0.96      0.96       197

In [109]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.9591380026711848

Once feature scaling is applied, recall on positive class jumps from ~50% to 96%. This shows that feature scaling was critical for the model. We can attempt to further boost performance with hyperparameter tuning

### Parameter Tuning

In [110]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [111]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-25 21:17:42,331] A new study created in memory with name: no-name-f9c73a74-00b7-413a-867a-b068e06a5386
[I 2026-06-25 21:17:42,369] Trial 0 finished with value: 0.8552742616033756 and parameters: {'C': 0.5262410341807104, 'kernel': 'rbf', 'coef0': 0.8409451651443367, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8552742616033756.
[I 2026-06-25 21:17:42,399] Trial 1 finished with value: 0.7539110678351185 and parameters: {'C': 0.046959014412427, 'kernel': 'sigmoid', 'coef0': 0.20946218731171606, 'Class_weight': None}. Best is trial 0 with value: 0.8552742616033756.
[I 2026-06-25 21:17:42,431] Trial 2 finished with value: 0.8096721843557286 and parameters: {'C': 0.22972773150858405, 'kernel': 'sigmoid', 'coef0': 0.18940633309503907, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8552742616033756.
[I 2026-06-25 21:17:42,462] Trial 3 finished with value: 0.8705290490100616 and parameters: {'C': 0.9077962015636515, 'kernel': 'rbf', 'coef0': 0.8708990560343293, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,477] Trial 4 finished with value: 0.840084388185654 and parameters: {'C': 0.8210927849906509, 'kernel': 'sigmoid', 'coef0': 0.18376876476584658, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,508] Trial 5 finished with value: 0.8502109704641351 and parameters: {'C': 0.9886279154666453, 'kernel': 'sigmoid', 'coef0': 0.4605234586135615, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,523] Trial 6 finished with value: 0.8046088932164881 and parameters: {'C': 0.1721053353056142, 'kernel': 'sigmoid', 'coef0': 0.26090354651406156, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,554] Trial 7 finished with value: 0.7408633560532295 and parameters: {'C': 0.009854701449023475, 'kernel': 'rbf', 'coef0': 0.029288666287469622, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,586] Trial 8 finished with value: 0.8502109704641351 and parameters: {'C': 0.434669523013697, 'kernel': 'rbf', 'coef0': 0.8440044883732238, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,617] Trial 9 finished with value: 0.8324894514767933 and parameters: {'C': 0.9064998811251368, 'kernel': 'sigmoid', 'coef0': 0.5470493240290885, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,648] Trial 10 finished with value: 0.8629016553067187 and parameters: {'C': 0.703183044713629, 'kernel': 'rbf', 'coef0': 0.6702245302670679, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,678] Trial 11 finished with value: 0.8629016553067187 and parameters: {'C': 0.6933195885432475, 'kernel': 'rbf', 'coef0': 0.9530799274085928, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,709] Trial 12 finished with value: 0.8629016553067187 and parameters: {'C': 0.7085737308365943, 'kernel': 'rbf', 'coef0': 0.6719425395927746, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,740] Trial 13 finished with value: 0.8629016553067187 and parameters: {'C': 0.6566093717607153, 'kernel': 'rbf', 'coef0': 0.6926253194865984, 'Class_weight': None}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,771] Trial 14 finished with value: 0.8654657578708213 and parameters: {'C': 0.8236437386241919, 'kernel': 'rbf', 'coef0': 0.7121269927640509, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.8705290490100616.
[I 2026-06-25 21:17:42,802] Trial 15 finished with value: 0.8705290490100618 and parameters: {'C': 0.8545866499938103, 'kernel': 'rbf', 'coef0': 0.9870395416816086, 'Class_weight': 'balanced'}. Best is trial 15 with value: 0.8705290490100618.
[I 2026-06-25 21:17:42,818] Trial 16 finished with value: 0.8527426160337553 and parameters: {'C': 0.5087146972864635, 'kernel': 'rbf', 'coef0': 0.9706915619591381, 'Class_weight': 'balanced'}. Best is trial 15 with value: 0.8705290490100618.
[I 2026-06-25 21:17:42,849] Trial 17 finished with value: 0.8730606945796818 and parameters: {'C': 0.955304466883955, 'kernel': 'rbf', 'coef0': 0.8879836467565744, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:42,880] Trial 18 finished with value: 0.8730606945796818 and parameters: {'C': 0.9854175910090384, 'kernel': 'rbf', 'coef0': 0.988797862840886, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:42,911] Trial 19 finished with value: 0.8730606945796818 and parameters: {'C': 0.9846807728836087, 'kernel': 'rbf', 'coef0': 0.5098867443639301, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:42,943] Trial 20 finished with value: 0.8502109704641351 and parameters: {'C': 0.4212003499962227, 'kernel': 'rbf', 'coef0': 0.7752238656934546, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:42,974] Trial 21 finished with value: 0.8730606945796818 and parameters: {'C': 0.9863348577071571, 'kernel': 'rbf', 'coef0': 0.5105575185164657, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,004] Trial 22 finished with value: 0.8730606945796818 and parameters: {'C': 0.9884970808793636, 'kernel': 'rbf', 'coef0': 0.38854523895259874, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,035] Trial 23 finished with value: 0.8654657578708213 and parameters: {'C': 0.7844353638128415, 'kernel': 'rbf', 'coef0': 0.6112672089559058, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,053] Trial 24 finished with value: 0.8679974034404415 and parameters: {'C': 0.9040352126652821, 'kernel': 'rbf', 'coef0': 0.9112453329117145, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,087] Trial 25 finished with value: 0.8629016553067187 and parameters: {'C': 0.6273540717381366, 'kernel': 'rbf', 'coef0': 0.8030841766291785, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,112] Trial 26 finished with value: 0.8679974034404415 and parameters: {'C': 0.9014227758161998, 'kernel': 'rbf', 'coef0': 0.34464470730731034, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,144] Trial 27 finished with value: 0.8654657578708213 and parameters: {'C': 0.7634476054848472, 'kernel': 'rbf', 'coef0': 0.7548483820369686, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,175] Trial 28 finished with value: 0.8730606945796818 and parameters: {'C': 0.9941201148247818, 'kernel': 'rbf', 'coef0': 0.05294490632057308, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,206] Trial 29 finished with value: 0.8603375527426161 and parameters: {'C': 0.5699700644727204, 'kernel': 'rbf', 'coef0': 0.8979664733033971, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,238] Trial 30 finished with value: 0.8502109704641351 and parameters: {'C': 0.35377908486322496, 'kernel': 'rbf', 'coef0': 0.5940090667141339, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,269] Trial 31 finished with value: 0.8730606945796818 and parameters: {'C': 0.95006546168394, 'kernel': 'rbf', 'coef0': 0.4832256849426193, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,300] Trial 32 finished with value: 0.8705290490100618 and parameters: {'C': 0.8576150261137729, 'kernel': 'rbf', 'coef0': 0.38920703194072936, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,316] Trial 33 finished with value: 0.8730606945796818 and parameters: {'C': 0.9458227622706986, 'kernel': 'rbf', 'coef0': 0.5449296082292507, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,332] Trial 34 finished with value: 0.8147679324894515 and parameters: {'C': 0.7629213947898591, 'kernel': 'sigmoid', 'coef0': 0.8178974392709799, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,348] Trial 35 finished with value: 0.8730606945796818 and parameters: {'C': 0.9358324982883098, 'kernel': 'rbf', 'coef0': 0.4352026009532995, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,363] Trial 36 finished with value: 0.8375527426160337 and parameters: {'C': 0.8719350600964214, 'kernel': 'sigmoid', 'coef0': 0.28039793339790403, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,394] Trial 37 finished with value: 0.8730606945796818 and parameters: {'C': 0.9949704630111501, 'kernel': 'rbf', 'coef0': 0.09559003160423524, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,410] Trial 38 finished with value: 0.786854917234664 and parameters: {'C': 0.1474098397659538, 'kernel': 'sigmoid', 'coef0': 0.5306819748887776, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,442] Trial 39 finished with value: 0.8654657578708213 and parameters: {'C': 0.8100820015463772, 'kernel': 'rbf', 'coef0': 0.6280570676335656, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,473] Trial 40 finished with value: 0.779227523531321 and parameters: {'C': 0.2767803198753999, 'kernel': 'sigmoid', 'coef0': 0.9279772582253504, 'Class_weight': None}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,504] Trial 41 finished with value: 0.8730606945796818 and parameters: {'C': 0.9952330881465136, 'kernel': 'rbf', 'coef0': 0.3382069279499351, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,520] Trial 42 finished with value: 0.8730606945796818 and parameters: {'C': 0.9450233620213065, 'kernel': 'rbf', 'coef0': 0.4129474853121767, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,536] Trial 43 finished with value: 0.8730606945796818 and parameters: {'C': 0.9435134974078188, 'kernel': 'rbf', 'coef0': 0.2303065567168831, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,567] Trial 44 finished with value: 0.8705290490100618 and parameters: {'C': 0.8727678798231303, 'kernel': 'rbf', 'coef0': 0.34821295574511457, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,598] Trial 45 finished with value: 0.8730606945796818 and parameters: {'C': 0.9641233435412842, 'kernel': 'rbf', 'coef0': 0.15261785623091684, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,628] Trial 46 finished with value: 0.8730606945796818 and parameters: {'C': 0.919202854965432, 'kernel': 'rbf', 'coef0': 0.8722595432436758, 'Class_weight': None}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,660] Trial 47 finished with value: 0.8654657578708213 and parameters: {'C': 0.827514160371702, 'kernel': 'rbf', 'coef0': 0.5012912962281835, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,691] Trial 48 finished with value: 0.8679974034404415 and parameters: {'C': 0.8890143988112114, 'kernel': 'rbf', 'coef0': 0.2930465339923587, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,798] Trial 49 finished with value: 0.8097046413502109 and parameters: {'C': 0.9973343653342539, 'kernel': 'sigmoid', 'coef0': 0.9989846677757293, 'Class_weight': None}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,830] Trial 50 finished with value: 0.8629016553067187 and parameters: {'C': 0.7310634430755049, 'kernel': 'rbf', 'coef0': 0.4447179135270842, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,861] Trial 51 finished with value: 0.8730606945796818 and parameters: {'C': 0.9967906698179149, 'kernel': 'rbf', 'coef0': 0.02404884150218828, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,892] Trial 52 finished with value: 0.8730606945796818 and parameters: {'C': 0.9593562789675412, 'kernel': 'rbf', 'coef0': 0.14420290741117553, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,923] Trial 53 finished with value: 0.8679974034404415 and parameters: {'C': 0.842595080962625, 'kernel': 'rbf', 'coef0': 0.0706603613172111, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,954] Trial 54 finished with value: 0.8705290490100616 and parameters: {'C': 0.9083087860463886, 'kernel': 'rbf', 'coef0': 0.5858084998816366, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:43,984] Trial 55 finished with value: 0.8730606945796818 and parameters: {'C': 0.966585792594445, 'kernel': 'rbf', 'coef0': 0.23320447151729345, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,015] Trial 56 finished with value: 0.8654657578708213 and parameters: {'C': 0.7920583305552982, 'kernel': 'rbf', 'coef0': 0.9510353788191095, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,046] Trial 57 finished with value: 0.8705290490100616 and parameters: {'C': 0.9106924526707381, 'kernel': 'rbf', 'coef0': 0.6470509159040396, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,077] Trial 58 finished with value: 0.8679974034404415 and parameters: {'C': 0.8757339508462724, 'kernel': 'rbf', 'coef0': 0.763164090077743, 'Class_weight': None}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,111] Trial 59 finished with value: 0.8578059071729959 and parameters: {'C': 0.5502858245930815, 'kernel': 'rbf', 'coef0': 0.3824925517911898, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,142] Trial 60 finished with value: 0.8730606945796818 and parameters: {'C': 0.9745684394905166, 'kernel': 'rbf', 'coef0': 0.7049647194033429, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,172] Trial 61 finished with value: 0.8730606945796818 and parameters: {'C': 0.9303791724376461, 'kernel': 'rbf', 'coef0': 0.5027449101300726, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,203] Trial 62 finished with value: 0.8730606945796818 and parameters: {'C': 0.9712733691848586, 'kernel': 'rbf', 'coef0': 0.5602662222234587, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,234] Trial 63 finished with value: 0.8730606945796818 and parameters: {'C': 0.9315884467095571, 'kernel': 'rbf', 'coef0': 0.8739278889772288, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,265] Trial 64 finished with value: 0.8502109704641351 and parameters: {'C': 0.4609906454062172, 'kernel': 'rbf', 'coef0': 0.5167105610579347, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,297] Trial 65 finished with value: 0.8679974034404415 and parameters: {'C': 0.8478518154302208, 'kernel': 'rbf', 'coef0': 0.4789760237176991, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,327] Trial 66 finished with value: 0.8679974034404415 and parameters: {'C': 0.8895489623986397, 'kernel': 'rbf', 'coef0': 0.4660918988083735, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,357] Trial 67 finished with value: 0.819831223628692 and parameters: {'C': 0.9645944970644965, 'kernel': 'sigmoid', 'coef0': 0.8300002553950272, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,388] Trial 68 finished with value: 0.8730606945796818 and parameters: {'C': 0.9977170818697997, 'kernel': 'rbf', 'coef0': 0.5806944810350585, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,419] Trial 69 finished with value: 0.8730606945796818 and parameters: {'C': 0.9220191115956482, 'kernel': 'rbf', 'coef0': 0.40291971234362045, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,450] Trial 70 finished with value: 0.8249269717624148 and parameters: {'C': 0.06410258987816664, 'kernel': 'rbf', 'coef0': 0.31418191705581344, 'Class_weight': None}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,480] Trial 71 finished with value: 0.8730606945796818 and parameters: {'C': 0.9440645352580649, 'kernel': 'rbf', 'coef0': 0.5466244420971219, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,512] Trial 72 finished with value: 0.8730606945796818 and parameters: {'C': 0.9463784777874855, 'kernel': 'rbf', 'coef0': 0.46696428198002227, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,542] Trial 73 finished with value: 0.8679974034404415 and parameters: {'C': 0.8914180167109381, 'kernel': 'rbf', 'coef0': 0.4272425817424053, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,573] Trial 74 finished with value: 0.8629016553067187 and parameters: {'C': 0.6425250480411232, 'kernel': 'rbf', 'coef0': 0.7280820691210266, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,605] Trial 75 finished with value: 0.8730606945796818 and parameters: {'C': 0.9726865007940597, 'kernel': 'rbf', 'coef0': 0.6591353499546012, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,637] Trial 76 finished with value: 0.8502109704641351 and parameters: {'C': 0.8680137470947513, 'kernel': 'sigmoid', 'coef0': 0.36710985862957374, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,667] Trial 77 finished with value: 0.8654657578708213 and parameters: {'C': 0.8065804089028191, 'kernel': 'rbf', 'coef0': 0.7910327721032958, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,698] Trial 78 finished with value: 0.8730606945796818 and parameters: {'C': 0.9163706407310366, 'kernel': 'rbf', 'coef0': 0.9423302140115788, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,729] Trial 79 finished with value: 0.8476793248945148 and parameters: {'C': 0.33604180643329273, 'kernel': 'rbf', 'coef0': 0.6091036329665109, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.
[I 2026-06-25 21:17:44,760] Trial 80 finished with value: 0.8679974034404415 and parameters: {'C': 0.8361200833585669, 'kernel': 'rbf', 'coef0': 0.8979227883913941, 'Class_weight': 'balanced'}. Best is trial 17 with value: 0.8730606945796818.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
33,33,0.873061,2026-06-25 21:17:43.300689,2026-06-25 21:17:43.316753,0 days 00:00:00.016064,0.945823,balanced,0.544930,rbf,COMPLETE
18,18,0.873061,2026-06-25 21:17:42.849195,2026-06-25 21:17:42.880930,0 days 00:00:00.031735,0.985418,balanced,0.988798,rbf,COMPLETE
17,17,0.873061,2026-06-25 21:17:42.818587,2026-06-25 21:17:42.849195,0 days 00:00:00.030608,0.955304,balanced,0.887984,rbf,COMPLETE
19,19,0.873061,2026-06-25 21:17:42.880930,2026-06-25 21:17:42.911778,0 days 00:00:00.030848,0.984681,balanced,0.509887,rbf,COMPLETE
35,35,0.873061,2026-06-25 21:17:43.332818,2026-06-25 21:17:43.348857,0 days 00:00:00.016039,0.935832,balanced,0.435203,rbf,COMPLETE

In [112]:
top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C']

np.float64(0.9458227622706986)

In [113]:
model = SVC(
    C=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C'],
    kernel=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_kernel'],
    # degree=degree,
    coef0=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_coef0'],
    # shrinking=shrinking,
    class_weight=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_Class_weight'],
    random_state=random_state,
    cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
)

In [114]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
print(classification_report(y_pred=y_pred, y_true=y_test))
None

              precision    recall  f1-score   support

           0       0.94      0.99      0.97        99
           1       0.99      0.94      0.96        98

    accuracy                           0.96       197
   macro avg       0.97      0.96      0.96       197
weighted avg       0.97      0.96      0.96       197

In [115]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.9591380026711848

Model overfit due to limited number of samples

## PPP

In [116]:
classification_reports = []
classification_report_keys = []

### Data

In [117]:
# Import IBM dataset
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/ppp_cleaned.csv')
df

,ProcessingMethod,BorrowerState,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,ServicingLenderState,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,...,MORTGAGE_INTEREST_PROCEED_pct,RENT_PROCEED_pct,REFINANCE_EIDL_PROCEED_pct,HEALTH_CARE_PROCEED_pct,DEBT_INTEREST_PROCEED_pct,PROCEED_Per_Job,Fraud,DateApproved_int,ForgivenessDate_int,LoanStatusDate_int
0,0.0,48.0,2.0,24,769358.78,769358.78,11.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,12409.01,0,1588291200,1605830400,1608249600
1,0.0,48.0,2.0,24,736927.79,736927.79,11.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,10094.90,0,1588291200,1628726400,1632787200
2,0.0,48.0,2.0,24,691355.00,691355.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,9218.07,0,1588291200,1612915200,1615939200
3,0.0,48.0,2.0,24,499871.00,499871.00,29.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,23803.38,0,1588291200,1631232000,1634342400
4,0.0,48.0,2.0,24,367437.00,367437.00,37.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,14697.48,0,1588291200,1617840000,1629158400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968527,0.0,56.0,2.0,24,150000.00,150000.00,54.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10000.00,0,1585872000,1607472000,1610496000
968528,0.0,56.0,2.0,24,150000.00,150000.00,31.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3452.38,0,1586822400,1604361600,1607385600
968529,1.0,56.0,2.0,60,150000.00,150000.00,54.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,29999.40,0,1613088000,1629158400,1631664000
968530,0.0,56.0,2.0,60,150000.00,150000.00,18.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,21428.57,0,1586908800,1645574400,1646697600
968531,0.0,56.0,2.0,24,150000.00,150000.00,54.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13636.36,0,1586390400,1632268800,1634860800

### Undersampling

In [118]:
from collections import Counter


X = df.drop(columns='Fraud')
y = df['Fraud']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 968437, 1: 95})
Resampled dataset shape: Counter({0: 95, 1: 95})

### Split Data

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

In [120]:
from sklearn.svm import SVC

# Using classifier since this is a fraud dataset with binary Y/N target
model = SVC()

In [121]:
model.fit(X_train, y_train)

SVC()

In [122]:
y_pred = model.predict(X_test)

In [123]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       1.00      0.74      0.85        19
           1       0.79      1.00      0.88        19

    accuracy                           0.87        38
   macro avg       0.90      0.87      0.87        38
weighted avg       0.90      0.87      0.87        38

In [124]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.7916666666666666

We see strong performance already without scaling

### Feature Scaling

In [125]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [126]:
model.fit(X_train_scaled, y_train)

SVC()

In [127]:
y_pred = model.predict(X_test_scaled)

In [128]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline SVM Classifier')

              precision    recall  f1-score   support

           0       0.93      0.74      0.82        19
           1       0.78      0.95      0.86        19

    accuracy                           0.84        38
   macro avg       0.86      0.84      0.84        38
weighted avg       0.86      0.84      0.84        38

Feature scaling does not affect this dataset

In [129]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.7677345537757436

### Parameter Tuning

In [130]:
from sklearn.model_selection import StratifiedKFold

# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
cv = StratifiedKFold(n_splits=5) # Using stratified to maintain class distribution

In [131]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    kernel = trial.suggest_categorical("kernel", ["rbf", "sigmoid"])
    # degree = trial.suggest_int("degree", 2, 5) # degree of kernal function in case of 'poly'
    coef0 = trial.suggest_float("coef0", 0.0, 1.0) # Independent term in kernel function. It is only significant in ‘poly’ and ‘sigmoid’.
    # shrinking = trial.suggest_categorical("shrinking", [True, False])
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])

    model = SVC(
        C=c,
        kernel=kernel,
        # degree=degree,
        coef0=coef0,
        # shrinking=shrinking,
        class_weight=class_weight,
        random_state=random_state,
        cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_svc_scaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_svc_scaled_recall_optuna_results)

[I 2026-06-25 21:17:47,664] A new study created in memory with name: no-name-3a5a0cec-5221-468b-829d-ad5e2a65e877
[I 2026-06-25 21:17:47,690] Trial 0 finished with value: 0.8949999999999999 and parameters: {'C': 0.16805526224121387, 'kernel': 'sigmoid', 'coef0': 0.7920980123473605, 'Class_weight': None}. Best is trial 0 with value: 0.8949999999999999.
[I 2026-06-25 21:17:47,705] Trial 1 finished with value: 0.8833333333333332 and parameters: {'C': 0.6497884372342807, 'kernel': 'rbf', 'coef0': 0.2679829683396697, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8949999999999999.
[I 2026-06-25 21:17:47,721] Trial 2 finished with value: 0.7533333333333334 and parameters: {'C': 0.0951417433054543, 'kernel': 'rbf', 'coef0': 0.41431630444557777, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8949999999999999.
[I 2026-06-25 21:17:47,737] Trial 3 finished with value: 0.9083333333333332 and parameters: {'C': 0.6225021351142411, 'kernel': 'sigmoid', 'coef0': 0.6505617049598637, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,752] Trial 4 finished with value: 0.8833333333333332 and parameters: {'C': 0.6202845251183905, 'kernel': 'rbf', 'coef0': 0.8190719728781103, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,768] Trial 5 finished with value: 0.9083333333333332 and parameters: {'C': 0.8251099837086066, 'kernel': 'sigmoid', 'coef0': 0.5203580372829497, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,783] Trial 6 finished with value: 0.9083333333333332 and parameters: {'C': 0.7713011220795993, 'kernel': 'sigmoid', 'coef0': 0.5507089121185301, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,799] Trial 7 finished with value: 0.9083333333333332 and parameters: {'C': 0.3016030746162817, 'kernel': 'sigmoid', 'coef0': 0.5184652849384743, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,815] Trial 8 finished with value: 0.8308333333333333 and parameters: {'C': 0.2112662891902052, 'kernel': 'rbf', 'coef0': 0.5401617525446657, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,830] Trial 9 finished with value: 0.9083333333333332 and parameters: {'C': 0.6376781422030329, 'kernel': 'sigmoid', 'coef0': 0.8762099761008088, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,846] Trial 10 finished with value: 0.9083333333333332 and parameters: {'C': 0.9780691679655552, 'kernel': 'sigmoid', 'coef0': 0.14793051702065407, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,862] Trial 11 finished with value: 0.9083333333333332 and parameters: {'C': 0.9022080535793906, 'kernel': 'sigmoid', 'coef0': 0.6657462798545746, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,877] Trial 12 finished with value: 0.9083333333333332 and parameters: {'C': 0.404702323213026, 'kernel': 'sigmoid', 'coef0': 0.9916999192466475, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,892] Trial 13 finished with value: 0.9083333333333332 and parameters: {'C': 0.792925686868581, 'kernel': 'sigmoid', 'coef0': 0.3557997182769913, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,923] Trial 14 finished with value: 0.9083333333333332 and parameters: {'C': 0.49263299681884515, 'kernel': 'sigmoid', 'coef0': 0.7067294101079721, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,939] Trial 15 finished with value: 0.9083333333333332 and parameters: {'C': 0.7843111283291127, 'kernel': 'sigmoid', 'coef0': 0.055722298725280284, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,955] Trial 16 finished with value: 0.9083333333333332 and parameters: {'C': 0.5053087097612171, 'kernel': 'sigmoid', 'coef0': 0.6471739312658175, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,970] Trial 17 finished with value: 0.9083333333333332 and parameters: {'C': 0.8902877294100217, 'kernel': 'sigmoid', 'coef0': 0.38891218396232546, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:47,986] Trial 18 finished with value: 0.8833333333333332 and parameters: {'C': 0.7078352022651792, 'kernel': 'rbf', 'coef0': 0.24701654939388662, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,001] Trial 19 finished with value: 0.9083333333333332 and parameters: {'C': 0.5088450168670752, 'kernel': 'sigmoid', 'coef0': 0.5942676770697165, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,018] Trial 20 finished with value: 0.9083333333333332 and parameters: {'C': 0.9830872180528473, 'kernel': 'sigmoid', 'coef0': 0.7466789780982521, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,033] Trial 21 finished with value: 0.9083333333333332 and parameters: {'C': 0.7750125332276072, 'kernel': 'sigmoid', 'coef0': 0.5202554132249777, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,059] Trial 22 finished with value: 0.9083333333333332 and parameters: {'C': 0.8412813948506752, 'kernel': 'sigmoid', 'coef0': 0.6027812531761502, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,074] Trial 23 finished with value: 0.9083333333333332 and parameters: {'C': 0.5787510867863757, 'kernel': 'sigmoid', 'coef0': 0.451349597138515, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,089] Trial 24 finished with value: 0.9083333333333332 and parameters: {'C': 0.7262918983526729, 'kernel': 'sigmoid', 'coef0': 0.3093346293387452, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,121] Trial 25 finished with value: 0.9083333333333332 and parameters: {'C': 0.6906135100684268, 'kernel': 'sigmoid', 'coef0': 0.46173810060293063, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,144] Trial 26 finished with value: 0.8833333333333332 and parameters: {'C': 0.8869702908994964, 'kernel': 'rbf', 'coef0': 0.5849123491231637, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,173] Trial 27 finished with value: 0.9083333333333332 and parameters: {'C': 0.3994326609634307, 'kernel': 'sigmoid', 'coef0': 0.8576029803521296, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,189] Trial 28 finished with value: 0.9083333333333332 and parameters: {'C': 0.8186716656983927, 'kernel': 'sigmoid', 'coef0': 0.6998470256974197, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,204] Trial 29 finished with value: 0.9083333333333332 and parameters: {'C': 0.5671464818778085, 'kernel': 'sigmoid', 'coef0': 0.7416406647504198, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,220] Trial 30 finished with value: 0.9083333333333332 and parameters: {'C': 0.7049837864349632, 'kernel': 'sigmoid', 'coef0': 0.4635316546345931, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,250] Trial 31 finished with value: 0.9083333333333332 and parameters: {'C': 0.2531570322352917, 'kernel': 'sigmoid', 'coef0': 0.535904101712813, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,265] Trial 32 finished with value: 0.9083333333333332 and parameters: {'C': 0.32705244379488285, 'kernel': 'sigmoid', 'coef0': 0.6131883457036305, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,281] Trial 33 finished with value: 0.745 and parameters: {'C': 0.0335736617674694, 'kernel': 'sigmoid', 'coef0': 0.5435811369273145, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,312] Trial 34 finished with value: 0.8175000000000001 and parameters: {'C': 0.15336128964792317, 'kernel': 'rbf', 'coef0': 0.33745910592451167, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,328] Trial 35 finished with value: 0.8833333333333332 and parameters: {'C': 0.42134340214296206, 'kernel': 'rbf', 'coef0': 0.4144648846127997, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,344] Trial 36 finished with value: 0.9083333333333332 and parameters: {'C': 0.3350459636177756, 'kernel': 'sigmoid', 'coef0': 0.23234700890267546, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,374] Trial 37 finished with value: 0.9083333333333332 and parameters: {'C': 0.6181151548371235, 'kernel': 'sigmoid', 'coef0': 0.7850405672664158, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,390] Trial 38 finished with value: 0.8833333333333332 and parameters: {'C': 0.6630768366746052, 'kernel': 'rbf', 'coef0': 0.6572591596877498, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,420] Trial 39 finished with value: 0.9083333333333332 and parameters: {'C': 0.7440356738613455, 'kernel': 'sigmoid', 'coef0': 0.5181621284182345, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,436] Trial 40 finished with value: 0.9083333333333332 and parameters: {'C': 0.5731325370365, 'kernel': 'sigmoid', 'coef0': 0.9501154905584916, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,466] Trial 41 finished with value: 0.9083333333333332 and parameters: {'C': 0.633783671793862, 'kernel': 'sigmoid', 'coef0': 0.9018767913019149, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,497] Trial 42 finished with value: 0.9083333333333332 and parameters: {'C': 0.8453716395406452, 'kernel': 'sigmoid', 'coef0': 0.8279395643384645, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,513] Trial 43 finished with value: 0.9083333333333332 and parameters: {'C': 0.9448419320591577, 'kernel': 'sigmoid', 'coef0': 0.4850210033664215, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,528] Trial 44 finished with value: 0.9083333333333332 and parameters: {'C': 0.4695655914677503, 'kernel': 'sigmoid', 'coef0': 0.4105502268924783, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,559] Trial 45 finished with value: 0.9083333333333332 and parameters: {'C': 0.7611151555497933, 'kernel': 'sigmoid', 'coef0': 0.5590631413964153, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,576] Trial 46 finished with value: 0.9083333333333332 and parameters: {'C': 0.6509936632132663, 'kernel': 'sigmoid', 'coef0': 0.6484935730708963, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,607] Trial 47 finished with value: 0.9083333333333332 and parameters: {'C': 0.5419142372100638, 'kernel': 'sigmoid', 'coef0': 0.7030050769680077, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,639] Trial 48 finished with value: 0.8833333333333332 and parameters: {'C': 0.9373905543730319, 'kernel': 'rbf', 'coef0': 0.8951595118816286, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,669] Trial 49 finished with value: 0.9083333333333332 and parameters: {'C': 0.2577848764810052, 'kernel': 'sigmoid', 'coef0': 0.7898016715713205, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,684] Trial 50 finished with value: 0.9083333333333332 and parameters: {'C': 0.6132274242866703, 'kernel': 'sigmoid', 'coef0': 0.3683604757195601, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,716] Trial 51 finished with value: 0.9083333333333332 and parameters: {'C': 0.9750947743094271, 'kernel': 'sigmoid', 'coef0': 0.016165622929605078, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,731] Trial 52 finished with value: 0.9083333333333332 and parameters: {'C': 0.866657465767376, 'kernel': 'sigmoid', 'coef0': 0.11709909716191885, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,746] Trial 53 finished with value: 0.9083333333333332 and parameters: {'C': 0.8110137967697084, 'kernel': 'sigmoid', 'coef0': 0.496407142883167, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,761] Trial 54 finished with value: 0.9083333333333332 and parameters: {'C': 0.6753848170518671, 'kernel': 'sigmoid', 'coef0': 0.12684350160961755, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,791] Trial 55 finished with value: 0.9083333333333332 and parameters: {'C': 0.79020269689348, 'kernel': 'sigmoid', 'coef0': 0.6162892952635449, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,822] Trial 56 finished with value: 0.9083333333333332 and parameters: {'C': 0.940840526802141, 'kernel': 'sigmoid', 'coef0': 0.995773624826741, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,852] Trial 57 finished with value: 0.9083333333333332 and parameters: {'C': 0.9102090119763354, 'kernel': 'sigmoid', 'coef0': 0.3237783621951221, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,868] Trial 58 finished with value: 0.9083333333333332 and parameters: {'C': 0.7455428027889085, 'kernel': 'sigmoid', 'coef0': 0.5785363069659195, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,883] Trial 59 finished with value: 0.8833333333333332 and parameters: {'C': 0.4632059870957236, 'kernel': 'rbf', 'coef0': 0.43308089329309957, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,899] Trial 60 finished with value: 0.9083333333333332 and parameters: {'C': 0.5319822048790985, 'kernel': 'sigmoid', 'coef0': 0.2758317146108378, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,914] Trial 61 finished with value: 0.9083333333333332 and parameters: {'C': 0.9996273596410591, 'kernel': 'sigmoid', 'coef0': 0.6809875002241109, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,945] Trial 62 finished with value: 0.9083333333333332 and parameters: {'C': 0.8983124012236019, 'kernel': 'sigmoid', 'coef0': 0.611084835045832, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:48,976] Trial 63 finished with value: 0.9083333333333332 and parameters: {'C': 0.8636411460856811, 'kernel': 'sigmoid', 'coef0': 0.7241271759632703, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,007] Trial 64 finished with value: 0.9083333333333332 and parameters: {'C': 0.822220835768262, 'kernel': 'sigmoid', 'coef0': 0.5606018473878558, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,022] Trial 65 finished with value: 0.9083333333333332 and parameters: {'C': 0.7174618386725223, 'kernel': 'sigmoid', 'coef0': 0.6668063722260422, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,038] Trial 66 finished with value: 0.9083333333333332 and parameters: {'C': 0.9178703970243667, 'kernel': 'sigmoid', 'coef0': 0.7701284299804623, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,068] Trial 67 finished with value: 0.9083333333333332 and parameters: {'C': 0.601290409480643, 'kernel': 'sigmoid', 'coef0': 0.4853525002697279, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,100] Trial 68 finished with value: 0.9083333333333332 and parameters: {'C': 0.1243814944504556, 'kernel': 'sigmoid', 'coef0': 0.17933298696485367, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,131] Trial 69 finished with value: 0.8833333333333332 and parameters: {'C': 0.8607978909658397, 'kernel': 'rbf', 'coef0': 0.5143140505708121, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,147] Trial 70 finished with value: 0.9083333333333332 and parameters: {'C': 0.9671499243666803, 'kernel': 'sigmoid', 'coef0': 0.8282499524812291, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,162] Trial 71 finished with value: 0.9083333333333332 and parameters: {'C': 0.40167342016383545, 'kernel': 'sigmoid', 'coef0': 0.9771396796906788, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,193] Trial 72 finished with value: 0.9083333333333332 and parameters: {'C': 0.3477492092931911, 'kernel': 'sigmoid', 'coef0': 0.9178744891763245, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,209] Trial 73 finished with value: 0.9083333333333332 and parameters: {'C': 0.2836486063545361, 'kernel': 'sigmoid', 'coef0': 0.6402827974904041, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,240] Trial 74 finished with value: 0.8949999999999999 and parameters: {'C': 0.1993644122629865, 'kernel': 'sigmoid', 'coef0': 0.9384381068089158, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,255] Trial 75 finished with value: 0.9083333333333332 and parameters: {'C': 0.3691194611409183, 'kernel': 'sigmoid', 'coef0': 0.8587327294563537, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,271] Trial 76 finished with value: 0.9083333333333332 and parameters: {'C': 0.44396837958164453, 'kernel': 'sigmoid', 'coef0': 0.8708484355532409, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,287] Trial 77 finished with value: 0.9083333333333332 and parameters: {'C': 0.2972229135631966, 'kernel': 'sigmoid', 'coef0': 0.45198141215666604, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,303] Trial 78 finished with value: 0.9083333333333332 and parameters: {'C': 0.4928319043031729, 'kernel': 'sigmoid', 'coef0': 0.752349408970107, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,334] Trial 79 finished with value: 0.8833333333333332 and parameters: {'C': 0.6861419736183011, 'kernel': 'rbf', 'coef0': 0.5432319640107331, 'Class_weight': None}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,350] Trial 80 finished with value: 0.9083333333333332 and parameters: {'C': 0.771019159013897, 'kernel': 'sigmoid', 'coef0': 0.6264493765234177, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.
[I 2026-06-25 21:17:49,366] Trial 81 finished with value: 0.9083333333333332 and parameters: {'C': 0.8284367377495229, 'kernel': 'sigmoid', 'coef0': 0.1996276113591058, 'Class_weight': 'balanced'}. Best is trial 3 with value: 0.9083333333333332.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,params_coef0,params_kernel,state
3,3,0.908333,2026-06-25 21:17:47.722866,2026-06-25 21:17:47.737386,0 days 00:00:00.014520,0.622502,None,0.650562,sigmoid,COMPLETE
7,7,0.908333,2026-06-25 21:17:47.783760,2026-06-25 21:17:47.799817,0 days 00:00:00.016057,0.301603,None,0.518465,sigmoid,COMPLETE
6,6,0.908333,2026-06-25 21:17:47.768512,2026-06-25 21:17:47.783760,0 days 00:00:00.015248,0.771301,balanced,0.550709,sigmoid,COMPLETE
5,5,0.908333,2026-06-25 21:17:47.752604,2026-06-25 21:17:47.768512,0 days 00:00:00.015908,0.825110,balanced,0.520358,sigmoid,COMPLETE
32,32,0.908333,2026-06-25 21:17:48.250482,2026-06-25 21:17:48.265510,0 days 00:00:00.015028,0.327052,None,0.613188,sigmoid,COMPLETE

In [132]:
model = SVC(
    C=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_C'],
    kernel=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_kernel'],
    # degree=degree,
    coef0=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_coef0'],
    # shrinking=shrinking,
    class_weight=top_5_svc_scaled_recall_optuna_results.iloc[0]['params_Class_weight'],
    random_state=random_state,
    cache_size=1000 # FIX 3: Increase RAM cache from default 200MB to 1GB
)

In [133]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
print(classification_report(y_pred=y_pred, y_true=y_test))
None

              precision    recall  f1-score   support

           0       1.00      0.74      0.85        19
           1       0.79      1.00      0.88        19

    accuracy                           0.87        38
   macro avg       0.90      0.87      0.87        38
weighted avg       0.90      0.87      0.87        38

In [134]:
average_precision_score(y_true=y_test, y_score=y_pred)

0.7916666666666666

The model generalized well