In [6]:
import pandas as pd
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
import optuna
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from collections import Counter

## Credit Card

In [7]:
classification_reports = []
classification_report_keys = []

In [8]:
random_state = 42

### Data

In [9]:
# Import credit card datasaet
df = pd.read_csv('C:/Users/caleb/Projects/BU Spring 2026/Module-B-semester-2/Milestone 3 EDA/credit_card_cleaned.csv')
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

### Undersampling

In [10]:
X = df.drop(columns='Class')
y = df['Class']
print("Original dataset shape:", Counter(y))
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

print("Resampled dataset shape:", Counter(y_resampled))

Original dataset shape: Counter({0: 284315, 1: 492})
Resampled dataset shape: Counter({0: 492, 1: 492})

### Split Data

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, 
                                                    y_resampled, 
                                                    test_size=0.2, 
                                                    stratify=y_resampled,  # Maintains class distribution
                                                    random_state=random_state
                                                    )

### Baseline Models
#### (No parameter optimization, feature scaling, or cross validation)

#### Linear Regression

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
y_pred = model.predict(X_test)

In [15]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Logistic Regression')

              precision    recall  f1-score   support

           0       0.96      0.93      0.94        99
           1       0.93      0.96      0.94        98

    accuracy                           0.94       197
   macro avg       0.94      0.94      0.94       197
weighted avg       0.94      0.94      0.94       197

#### Ridge

In [16]:
from sklearn.linear_model import RidgeClassifier


ridge_model = RidgeClassifier(random_state=random_state)

In [17]:
ridge_model.fit(X_train, y_train)

RidgeClassifier(random_state=42)

In [18]:
y_pred = ridge_model.predict(X_test)

In [19]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline Ridge Classifier')

              precision    recall  f1-score   support

           0       0.89      0.99      0.94        99
           1       0.99      0.88      0.93        98

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197

#### Lasso

In [20]:
lasso_model = LogisticRegression(penalty='l1', solver='liblinear')

In [21]:
lasso_model.fit(X_train, y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [22]:
y_pred = lasso_model.predict(X_test)

In [23]:
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Baseline L1 (Lasso) Logistic Regression')

              precision    recall  f1-score   support

           0       0.95      0.95      0.95        99
           1       0.95      0.95      0.95        98

    accuracy                           0.95       197
   macro avg       0.95      0.95      0.95       197
weighted avg       0.95      0.95      0.95       197

### Scaling Data

In [24]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Parameter Tuning

#### Logistic Regression

In [25]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [26]:
# cv = RepeatedKFold(n_splits=5, n_repeats=5, random_state=random_state)
from sklearn.model_selection import StratifiedKFold


cv = StratifiedKFold(n_splits=5)

In [27]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_recall_optuna_results)

[I 2026-06-24 19:35:38,615] A new study created in memory with name: no-name-646f10d6-ab43-41b3-bcc2-af4e429bd6e9
[I 2026-06-24 19:35:40,053] Trial 0 finished with value: 0.8907822135670237 and parameters: {'C': 0.8355770815861004, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:41,086] Trial 1 finished with value: 0.8857189224277832 and parameters: {'C': 0.32324092459265447, 'Class_weight': None}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:42,144] Trial 2 finished with value: 0.8907822135670237 and parameters: {'C': 0.6654281664652126, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,191] Trial 3 finished with value: 0.8907822135670237 and parameters: {'C': 0.8136240165337804, 'Class_weight': None}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,207] Trial 4 finished with value: 0.8907822135670237 and parameters: {'C': 0.9855053004116283, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,223] Trial 5 finished with value: 0.8831872768581629 and parameters: {'C': 0.3013622978318447, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,238] Trial 6 finished with value: 0.8806556312885426 and parameters: {'C': 0.200668453425485, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,254] Trial 7 finished with value: 0.8704965920155793 and parameters: {'C': 0.07788157242239824, 'Class_weight': None}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,270] Trial 8 finished with value: 0.8907822135670237 and parameters: {'C': 0.6906279550318755, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,286] Trial 9 finished with value: 0.8628691983122362 and parameters: {'C': 0.057245603085288706, 'Class_weight': None}. Best is trial 0 with value: 0.8907822135670237.
[I 2026-06-24 19:35:43,302] Trial 10 finished with value: 0.893313859136644 and parameters: {'C': 0.988118812158264, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,318] Trial 11 finished with value: 0.893313859136644 and parameters: {'C': 0.9982268381701779, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,344] Trial 12 finished with value: 0.8907822135670237 and parameters: {'C': 0.9474327722224345, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,360] Trial 13 finished with value: 0.8907822135670237 and parameters: {'C': 0.5420144652314467, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,376] Trial 14 finished with value: 0.8907822135670237 and parameters: {'C': 0.8508830552330909, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,392] Trial 15 finished with value: 0.8907822135670237 and parameters: {'C': 0.6450399921299543, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,407] Trial 16 finished with value: 0.8907822135670237 and parameters: {'C': 0.9661336451995813, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,423] Trial 17 finished with value: 0.8907822135670237 and parameters: {'C': 0.5080025040337534, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,439] Trial 18 finished with value: 0.8907822135670237 and parameters: {'C': 0.7828920038482519, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,465] Trial 19 finished with value: 0.8857189224277832 and parameters: {'C': 0.38785936903833634, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,481] Trial 20 finished with value: 0.8907822135670237 and parameters: {'C': 0.9060064556537224, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,495] Trial 21 finished with value: 0.8907822135670237 and parameters: {'C': 0.7421403760108083, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,511] Trial 22 finished with value: 0.8907822135670237 and parameters: {'C': 0.871972072098711, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,526] Trial 23 finished with value: 0.893313859136644 and parameters: {'C': 0.9969812066245425, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,542] Trial 24 finished with value: 0.893313859136644 and parameters: {'C': 0.998962135748188, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,563] Trial 25 finished with value: 0.8907822135670237 and parameters: {'C': 0.9008004650763083, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,579] Trial 26 finished with value: 0.8907822135670237 and parameters: {'C': 0.7365386784969072, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,595] Trial 27 finished with value: 0.8907822135670237 and parameters: {'C': 0.8942173627346248, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,610] Trial 28 finished with value: 0.8907822135670237 and parameters: {'C': 0.5648874479817759, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,626] Trial 29 finished with value: 0.8907822135670237 and parameters: {'C': 0.7998133237999852, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,641] Trial 30 finished with value: 0.8857189224277832 and parameters: {'C': 0.42206318236661367, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,666] Trial 31 finished with value: 0.893313859136644 and parameters: {'C': 0.9891756885281406, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,691] Trial 32 finished with value: 0.893313859136644 and parameters: {'C': 0.9906265174253458, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,706] Trial 33 finished with value: 0.8907822135670237 and parameters: {'C': 0.9230490198483398, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,722] Trial 34 finished with value: 0.8907822135670237 and parameters: {'C': 0.8331259855353845, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,740] Trial 35 finished with value: 0.893313859136644 and parameters: {'C': 0.995629601273803, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,768] Trial 36 finished with value: 0.8907822135670237 and parameters: {'C': 0.9252158263568978, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,793] Trial 37 finished with value: 0.8907822135670237 and parameters: {'C': 0.6215522341954943, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,818] Trial 38 finished with value: 0.8907822135670237 and parameters: {'C': 0.7442843690554745, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,833] Trial 39 finished with value: 0.8907822135670237 and parameters: {'C': 0.8541674943999463, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,848] Trial 40 finished with value: 0.8806556312885426 and parameters: {'C': 0.19275314653833242, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,864] Trial 41 finished with value: 0.8907822135670237 and parameters: {'C': 0.9299039565970066, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,880] Trial 42 finished with value: 0.893313859136644 and parameters: {'C': 0.9995932496988755, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,911] Trial 43 finished with value: 0.8907822135670237 and parameters: {'C': 0.9571573988355073, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,942] Trial 44 finished with value: 0.8907822135670237 and parameters: {'C': 0.945255616816004, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,959] Trial 45 finished with value: 0.8907822135670237 and parameters: {'C': 0.8698475135690853, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,974] Trial 46 finished with value: 0.8907822135670237 and parameters: {'C': 0.8082876354181737, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:43,990] Trial 47 finished with value: 0.893313859136644 and parameters: {'C': 0.9982133988186145, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,011] Trial 48 finished with value: 0.8907822135670237 and parameters: {'C': 0.9613003926886646, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,027] Trial 49 finished with value: 0.8907822135670237 and parameters: {'C': 0.877488868094806, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,043] Trial 50 finished with value: 0.8907822135670237 and parameters: {'C': 0.7719678979657295, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,059] Trial 51 finished with value: 0.8907822135670237 and parameters: {'C': 0.968152725294052, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,078] Trial 52 finished with value: 0.8907822135670237 and parameters: {'C': 0.9295984523250236, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,093] Trial 53 finished with value: 0.8907822135670237 and parameters: {'C': 0.9691083009476027, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,109] Trial 54 finished with value: 0.8907822135670237 and parameters: {'C': 0.8346057757797538, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,125] Trial 55 finished with value: 0.893313859136644 and parameters: {'C': 0.9946492434179084, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,141] Trial 56 finished with value: 0.8907822135670237 and parameters: {'C': 0.9058716975532239, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,157] Trial 57 finished with value: 0.8907822135670237 and parameters: {'C': 0.6891737821364816, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,173] Trial 58 finished with value: 0.8806556312885426 and parameters: {'C': 0.23683166997139143, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,188] Trial 59 finished with value: 0.8907822135670237 and parameters: {'C': 0.8896395065917029, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,204] Trial 60 finished with value: 0.8349886400519312 and parameters: {'C': 0.02209728184580545, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,220] Trial 61 finished with value: 0.8907822135670237 and parameters: {'C': 0.9770227768844212, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,234] Trial 62 finished with value: 0.8907822135670237 and parameters: {'C': 0.9463340150154822, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,249] Trial 63 finished with value: 0.893313859136644 and parameters: {'C': 0.9932264849342155, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,265] Trial 64 finished with value: 0.8907822135670237 and parameters: {'C': 0.9114144762730697, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,281] Trial 65 finished with value: 0.8907822135670237 and parameters: {'C': 0.9504137411556142, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,296] Trial 66 finished with value: 0.8907822135670237 and parameters: {'C': 0.8482174435909025, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,311] Trial 67 finished with value: 0.893313859136644 and parameters: {'C': 0.9998480694612478, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,327] Trial 68 finished with value: 0.8907822135670237 and parameters: {'C': 0.8807392140186838, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,342] Trial 69 finished with value: 0.8907822135670237 and parameters: {'C': 0.9277124802691559, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,369] Trial 70 finished with value: 0.8907822135670237 and parameters: {'C': 0.9579513472600517, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,387] Trial 71 finished with value: 0.893313859136644 and parameters: {'C': 0.989781631595246, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,403] Trial 72 finished with value: 0.8907822135670237 and parameters: {'C': 0.900900156094853, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,425] Trial 73 finished with value: 0.8907822135670237 and parameters: {'C': 0.9742864430582353, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,448] Trial 74 finished with value: 0.893313859136644 and parameters: {'C': 0.9988956505060733, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,466] Trial 75 finished with value: 0.8907822135670237 and parameters: {'C': 0.9329458200533557, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,481] Trial 76 finished with value: 0.8857189224277832 and parameters: {'C': 0.4104240745843483, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,498] Trial 77 finished with value: 0.8907822135670237 and parameters: {'C': 0.9422162671124952, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,513] Trial 78 finished with value: 0.8907822135670237 and parameters: {'C': 0.8677923350646032, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,528] Trial 79 finished with value: 0.8907822135670237 and parameters: {'C': 0.5961066820035823, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,542] Trial 80 finished with value: 0.8907822135670237 and parameters: {'C': 0.8234426220039197, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,568] Trial 81 finished with value: 0.8907822135670237 and parameters: {'C': 0.9670275162220909, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,583] Trial 82 finished with value: 0.893313859136644 and parameters: {'C': 0.9997478500467867, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,599] Trial 83 finished with value: 0.8907822135670237 and parameters: {'C': 0.9123575508841021, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,615] Trial 84 finished with value: 0.8907822135670237 and parameters: {'C': 0.9683594168471876, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,631] Trial 85 finished with value: 0.8907822135670237 and parameters: {'C': 0.9475341693368585, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,646] Trial 86 finished with value: 0.8907822135670237 and parameters: {'C': 0.9788552534015282, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,670] Trial 87 finished with value: 0.8907822135670237 and parameters: {'C': 0.9213027355343102, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,690] Trial 88 finished with value: 0.8857189224277832 and parameters: {'C': 0.33724026218050107, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,706] Trial 89 finished with value: 0.8907822135670237 and parameters: {'C': 0.8921912099458074, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,721] Trial 90 finished with value: 0.8907822135670237 and parameters: {'C': 0.9766995210808395, 'Class_weight': None}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,736] Trial 91 finished with value: 0.893313859136644 and parameters: {'C': 0.9952323100704188, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,752] Trial 92 finished with value: 0.8907822135670237 and parameters: {'C': 0.9495899685720212, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,767] Trial 93 finished with value: 0.8907822135670237 and parameters: {'C': 0.9792526872869903, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,783] Trial 94 finished with value: 0.893313859136644 and parameters: {'C': 0.9981693945314785, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,799] Trial 95 finished with value: 0.8907822135670237 and parameters: {'C': 0.9292316265668877, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,814] Trial 96 finished with value: 0.8882505679974034 and parameters: {'C': 0.47290191343401644, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,830] Trial 97 finished with value: 0.8907822135670237 and parameters: {'C': 0.9583891023686696, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,845] Trial 98 finished with value: 0.8907822135670237 and parameters: {'C': 0.8652172060969154, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.
[I 2026-06-24 19:35:44,866] Trial 99 finished with value: 0.8907822135670237 and parameters: {'C': 0.9076446769432984, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.893313859136644.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
35,35,0.893314,2026-06-24 19:35:43.722395,2026-06-24 19:35:43.740900,0 days 00:00:00.018505,0.995630,balanced,COMPLETE
24,24,0.893314,2026-06-24 19:35:43.526984,2026-06-24 19:35:43.542928,0 days 00:00:00.015944,0.998962,balanced,COMPLETE
11,11,0.893314,2026-06-24 19:35:43.302127,2026-06-24 19:35:43.318210,0 days 00:00:00.016083,0.998227,balanced,COMPLETE
10,10,0.893314,2026-06-24 19:35:43.286349,2026-06-24 19:35:43.302127,0 days 00:00:00.015778,0.988119,balanced,COMPLETE
31,31,0.893314,2026-06-24 19:35:43.641905,2026-06-24 19:35:43.666723,0 days 00:00:00.024818,0.989176,balanced,COMPLETE

In [28]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        class_weight=class_weight,
        C=c,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_log_reg_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_log_reg_unscaled_f1_optuna_results)

[I 2026-06-24 19:35:44,885] A new study created in memory with name: no-name-7b559d8b-9980-4dde-80f4-6cc483bcd45e
[I 2026-06-24 19:35:44,913] Trial 0 finished with value: 0.9309924060669379 and parameters: {'C': 0.9836845852940687, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:44,929] Trial 1 finished with value: 0.926405627137804 and parameters: {'C': 0.21005433861759773, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:44,945] Trial 2 finished with value: 0.9267929484786859 and parameters: {'C': 0.32954290205589837, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:44,972] Trial 3 finished with value: 0.9295807643799391 and parameters: {'C': 0.7421361264639691, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:44,993] Trial 4 finished with value: 0.9295807643799391 and parameters: {'C': 0.7178866304090076, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,009] Trial 5 finished with value: 0.9295807643799391 and parameters: {'C': 0.7849190532028982, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,028] Trial 6 finished with value: 0.9295807643799391 and parameters: {'C': 0.9287402408637013, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,044] Trial 7 finished with value: 0.9267929484786859 and parameters: {'C': 0.33831496654475884, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,067] Trial 8 finished with value: 0.9075992281742646 and parameters: {'C': 0.026094820379191083, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,084] Trial 9 finished with value: 0.926405627137804 and parameters: {'C': 0.1771175429911514, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,108] Trial 10 finished with value: 0.9295807643799391 and parameters: {'C': 0.5679581533698216, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,124] Trial 11 finished with value: 0.9309924060669379 and parameters: {'C': 0.9995147832591327, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,140] Trial 12 finished with value: 0.9309924060669379 and parameters: {'C': 0.9821994183651697, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,158] Trial 13 finished with value: 0.9295807643799391 and parameters: {'C': 0.8533344956693248, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,173] Trial 14 finished with value: 0.9295807643799391 and parameters: {'C': 0.582855048606023, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,189] Trial 15 finished with value: 0.9309924060669379 and parameters: {'C': 0.9966236807993357, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,204] Trial 16 finished with value: 0.9295807643799391 and parameters: {'C': 0.8545750562747483, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,220] Trial 17 finished with value: 0.9295807643799391 and parameters: {'C': 0.6288561943660046, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,236] Trial 18 finished with value: 0.9295807643799391 and parameters: {'C': 0.8936572671111916, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,250] Trial 19 finished with value: 0.92815030080378 and parameters: {'C': 0.44705841403043367, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,265] Trial 20 finished with value: 0.9295807643799391 and parameters: {'C': 0.6567241521741581, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,281] Trial 21 finished with value: 0.9295807643799391 and parameters: {'C': 0.978495128198196, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,297] Trial 22 finished with value: 0.9295807643799391 and parameters: {'C': 0.8095752657039845, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,312] Trial 23 finished with value: 0.9295807643799391 and parameters: {'C': 0.9274728350132243, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,338] Trial 24 finished with value: 0.9295807643799391 and parameters: {'C': 0.9613102072791216, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,356] Trial 25 finished with value: 0.9295807643799391 and parameters: {'C': 0.8842102071479261, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,372] Trial 26 finished with value: 0.9309924060669379 and parameters: {'C': 0.9955598690829389, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,384] Trial 27 finished with value: 0.9295807643799391 and parameters: {'C': 0.7121341573224329, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,399] Trial 28 finished with value: 0.9295807643799391 and parameters: {'C': 0.7852613051874928, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,414] Trial 29 finished with value: 0.92815030080378 and parameters: {'C': 0.45273231565450156, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,440] Trial 30 finished with value: 0.9295807643799391 and parameters: {'C': 0.8467374574325245, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,466] Trial 31 finished with value: 0.9309924060669379 and parameters: {'C': 0.9886559504372987, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,481] Trial 32 finished with value: 0.9295807643799391 and parameters: {'C': 0.9115125081888699, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,497] Trial 33 finished with value: 0.9309924060669379 and parameters: {'C': 0.9826803566273379, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,512] Trial 34 finished with value: 0.9295807643799391 and parameters: {'C': 0.9145146528229398, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,527] Trial 35 finished with value: 0.9295807643799391 and parameters: {'C': 0.7433130690167044, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,543] Trial 36 finished with value: 0.9295807643799391 and parameters: {'C': 0.8245634018145336, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,568] Trial 37 finished with value: 0.9295807643799391 and parameters: {'C': 0.9315728538491346, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,584] Trial 38 finished with value: 0.9295807643799391 and parameters: {'C': 0.7397367935982581, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,600] Trial 39 finished with value: 0.926405627137804 and parameters: {'C': 0.16530465825075685, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,628] Trial 40 finished with value: 0.9253432840491556 and parameters: {'C': 0.271963993847792, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,643] Trial 41 finished with value: 0.9309924060669379 and parameters: {'C': 0.99091382522028, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,666] Trial 42 finished with value: 0.9295807643799391 and parameters: {'C': 0.9363144637814411, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,681] Trial 43 finished with value: 0.9309924060669379 and parameters: {'C': 0.9961956289852446, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,696] Trial 44 finished with value: 0.9295807643799391 and parameters: {'C': 0.8853699748451341, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,711] Trial 45 finished with value: 0.9295807643799391 and parameters: {'C': 0.867235331005481, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,727] Trial 46 finished with value: 0.9295807643799391 and parameters: {'C': 0.9471347108799575, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,742] Trial 47 finished with value: 0.9295807643799391 and parameters: {'C': 0.7832640877187892, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,768] Trial 48 finished with value: 0.9238871473354232 and parameters: {'C': 0.06568741137739509, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,784] Trial 49 finished with value: 0.9309924060669379 and parameters: {'C': 0.9983431140205953, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,800] Trial 50 finished with value: 0.9295807643799391 and parameters: {'C': 0.831864532617602, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,829] Trial 51 finished with value: 0.9295807643799391 and parameters: {'C': 0.9499173765808077, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,845] Trial 52 finished with value: 0.9309924060669379 and parameters: {'C': 0.9996912275256262, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,866] Trial 53 finished with value: 0.9295807643799391 and parameters: {'C': 0.8973201240470502, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,895] Trial 54 finished with value: 0.9295807643799391 and parameters: {'C': 0.9503224526302431, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,911] Trial 55 finished with value: 0.9295807643799391 and parameters: {'C': 0.9600057665188559, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,928] Trial 56 finished with value: 0.9295807643799391 and parameters: {'C': 0.8784924418295332, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,942] Trial 57 finished with value: 0.9295807643799391 and parameters: {'C': 0.9125128289270683, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,969] Trial 58 finished with value: 0.9295807643799391 and parameters: {'C': 0.7905710055280903, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:45,993] Trial 59 finished with value: 0.9267929484786859 and parameters: {'C': 0.3748788889152205, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,008] Trial 60 finished with value: 0.9295807643799391 and parameters: {'C': 0.6640419295599912, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,024] Trial 61 finished with value: 0.9295807643799391 and parameters: {'C': 0.9651811266020478, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,040] Trial 62 finished with value: 0.9295807643799391 and parameters: {'C': 0.975049841800537, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,066] Trial 63 finished with value: 0.9295807643799391 and parameters: {'C': 0.5360511573225646, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,081] Trial 64 finished with value: 0.9295807643799391 and parameters: {'C': 0.8539843274799578, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,097] Trial 65 finished with value: 0.9295807643799391 and parameters: {'C': 0.9119055582515917, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,113] Trial 66 finished with value: 0.9295807643799391 and parameters: {'C': 0.9650218880130781, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,128] Trial 67 finished with value: 0.9309924060669379 and parameters: {'C': 0.9990796335264024, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,144] Trial 68 finished with value: 0.9295807643799391 and parameters: {'C': 0.9285701802094796, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,160] Trial 69 finished with value: 0.9295807643799391 and parameters: {'C': 0.8648786694899377, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,175] Trial 70 finished with value: 0.9295807643799391 and parameters: {'C': 0.9693038158344116, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,191] Trial 71 finished with value: 0.9309924060669379 and parameters: {'C': 0.9961464488249868, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,206] Trial 72 finished with value: 0.9295807643799391 and parameters: {'C': 0.9293869947656124, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,222] Trial 73 finished with value: 0.9295807643799391 and parameters: {'C': 0.8906170751233373, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,238] Trial 74 finished with value: 0.9295807643799391 and parameters: {'C': 0.9822254384224142, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,254] Trial 75 finished with value: 0.9295807643799391 and parameters: {'C': 0.9447211602636046, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,270] Trial 76 finished with value: 0.9295807643799391 and parameters: {'C': 0.9044108763473583, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,285] Trial 77 finished with value: 0.9295807643799391 and parameters: {'C': 0.9766648869185685, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,300] Trial 78 finished with value: 0.9295807643799391 and parameters: {'C': 0.8238180529585741, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,326] Trial 79 finished with value: 0.9295807643799391 and parameters: {'C': 0.9371950383591038, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,342] Trial 80 finished with value: 0.9295807643799391 and parameters: {'C': 0.9712151974551076, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,369] Trial 81 finished with value: 0.9309924060669379 and parameters: {'C': 0.9912634069171747, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,384] Trial 82 finished with value: 0.9309924060669379 and parameters: {'C': 0.9990183255224148, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,400] Trial 83 finished with value: 0.9295807643799391 and parameters: {'C': 0.9481188836060699, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,415] Trial 84 finished with value: 0.9295807643799391 and parameters: {'C': 0.9180501145410188, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,431] Trial 85 finished with value: 0.9295807643799391 and parameters: {'C': 0.8826848055281528, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,446] Trial 86 finished with value: 0.9295807643799391 and parameters: {'C': 0.955562340338084, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,466] Trial 87 finished with value: 0.9295807643799391 and parameters: {'C': 0.9044800941322693, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,482] Trial 88 finished with value: 0.9295807643799391 and parameters: {'C': 0.8474325345513649, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,498] Trial 89 finished with value: 0.9295807643799391 and parameters: {'C': 0.9716282130013092, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,527] Trial 90 finished with value: 0.9295807643799391 and parameters: {'C': 0.9353065430845644, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,542] Trial 91 finished with value: 0.9295807643799391 and parameters: {'C': 0.9853401423618194, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,558] Trial 92 finished with value: 0.9309924060669379 and parameters: {'C': 0.9955276050844991, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,573] Trial 93 finished with value: 0.9295807643799391 and parameters: {'C': 0.957730582502354, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,589] Trial 94 finished with value: 0.9309924060669379 and parameters: {'C': 0.9993209499202237, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,604] Trial 95 finished with value: 0.9295807643799391 and parameters: {'C': 0.9256679225838498, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,620] Trial 96 finished with value: 0.9295807643799391 and parameters: {'C': 0.952240788376938, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,635] Trial 97 finished with value: 0.9295807643799391 and parameters: {'C': 0.8939806970239339, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,650] Trial 98 finished with value: 0.9295807643799391 and parameters: {'C': 0.977868930063603, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9309924060669379.
[I 2026-06-24 19:35:46,667] Trial 99 finished with value: 0.9295807643799391 and parameters: {'C': 0.8644042520704491, 'Class_weight': None}. Best is trial 0 with value: 0.9309924060669379.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
0,0,0.930992,2026-06-24 19:35:44.886714,2026-06-24 19:35:44.913936,0 days 00:00:00.027222,0.983685,None,COMPLETE
15,15,0.930992,2026-06-24 19:35:45.173791,2026-06-24 19:35:45.189125,0 days 00:00:00.015334,0.996624,None,COMPLETE
12,12,0.930992,2026-06-24 19:35:45.124552,2026-06-24 19:35:45.140093,0 days 00:00:00.015541,0.982199,None,COMPLETE
11,11,0.930992,2026-06-24 19:35:45.108752,2026-06-24 19:35:45.124552,0 days 00:00:00.015800,0.999515,None,COMPLETE
31,31,0.930992,2026-06-24 19:35:45.440935,2026-06-24 19:35:45.466208,0 days 00:00:00.025273,0.988656,None,COMPLETE

##### Tryout best params

In [29]:
log_reg_recall_optimized_model = LogisticRegression(C=0.769946, class_weight='balanced', random_state=random_state)
log_reg_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.95      0.98      0.97        99
           1       0.98      0.95      0.96        98

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197

In [30]:
log_reg_f1_optimized_model = LogisticRegression(C=0.315005, class_weight='balanced', random_state=random_state)
log_reg_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = log_reg_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Logistic Regression (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.95      0.98      0.97        99
           1       0.98      0.95      0.96        98

    accuracy                           0.96       197
   macro avg       0.96      0.96      0.96       197
weighted avg       0.96      0.96      0.96       197

#### Ridge

In [31]:
# We can tune alpha and class weight

##### Recall optimized

In [32]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_recall_optuna_results)

[I 2026-06-24 19:35:46,762] A new study created in memory with name: no-name-1cd54852-5505-4051-92b8-1df93b950d0b
[I 2026-06-24 19:35:46,789] Trial 0 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.838181028632859, 'class_weight': None}. Best is trial 0 with value: 0.8324894514767933.
[I 2026-06-24 19:35:46,805] Trial 1 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.7195146637736881, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8324894514767933.
[I 2026-06-24 19:35:46,821] Trial 2 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4453398627247352, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,836] Trial 3 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.6956312528965283, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,850] Trial 4 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5612224814657214, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,867] Trial 5 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4743218405000634, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,883] Trial 6 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.39898093350243813, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,898] Trial 7 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.8157465662221933, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,913] Trial 8 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.21698248665002057, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,929] Trial 9 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.45747649756931436, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,945] Trial 10 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.08866718954549191, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,960] Trial 11 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.610264871231724, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:46,977] Trial 12 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.2712792624283948, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,000] Trial 13 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.583886947049934, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,014] Trial 14 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3709357022141077, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,032] Trial 15 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.9791705234980608, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,049] Trial 16 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.28103570055731414, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,064] Trial 17 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.06504739941150983, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,080] Trial 18 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.5622629818910561, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,096] Trial 19 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.16626316006543213, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,112] Trial 20 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.350532941050715, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,127] Trial 21 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.500438780714557, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,144] Trial 22 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.673680505905598, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,169] Trial 23 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.46180598716698684, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,184] Trial 24 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5674293509889394, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,199] Trial 25 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4182292838760492, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,214] Trial 26 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5259116239057512, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,230] Trial 27 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3188163456473898, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,246] Trial 28 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.6310040489972855, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,261] Trial 29 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.7454955906819739, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,277] Trial 30 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.8113820733995857, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,292] Trial 31 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.41078472916458064, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,307] Trial 32 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.49625628098597674, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,322] Trial 33 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4149718552876297, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,339] Trial 34 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.6542001221427918, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,354] Trial 35 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.2196143132285549, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,369] Trial 36 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.7466546005542631, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,384] Trial 37 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5328124927266535, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,400] Trial 38 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4517704300953721, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,416] Trial 39 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3289795691296733, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,431] Trial 40 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3933719416475213, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,447] Trial 41 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.14057464331845493, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,463] Trial 42 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.006246418584200858, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,478] Trial 43 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.248693781112916, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,494] Trial 44 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.19917277726661448, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,509] Trial 45 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.6028247142646358, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,524] Trial 46 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.46086290206879343, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,540] Trial 47 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3021116281386256, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,569] Trial 48 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.10829790517121896, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,584] Trial 49 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3722493911489641, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,600] Trial 50 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5366799710711166, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,615] Trial 51 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.48176094075845693, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,631] Trial 52 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.5833750117327399, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,645] Trial 53 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.9613302135963058, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,660] Trial 54 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.44139563455503417, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,676] Trial 55 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.34788546450158886, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,692] Trial 56 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.26758682430076963, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,707] Trial 57 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5394216857366068, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,723] Trial 58 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.37741779762636035, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,738] Trial 59 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.6318001075483631, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,753] Trial 60 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.709391312916872, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,769] Trial 61 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.0347289004444562, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,785] Trial 62 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.11652628684755112, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,801] Trial 63 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.07217496929052922, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,817] Trial 64 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.18269153900620236, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,833] Trial 65 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5088019279522539, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,848] Trial 66 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.22537728900141835, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,864] Trial 67 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5652327129180782, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,880] Trial 68 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.47491551049208347, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,895] Trial 69 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.433208059051, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,911] Trial 70 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.40005599346518356, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,927] Trial 71 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.34382969558226795, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,943] Trial 72 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.2936367674251403, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,959] Trial 73 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.15252499463409466, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,975] Trial 74 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4933237651956537, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:47,991] Trial 75 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.2483212927174036, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,007] Trial 76 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.42523628806309444, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,022] Trial 77 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3231802585002498, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,038] Trial 78 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.06325749200089724, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,054] Trial 79 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.21161497749667343, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,069] Trial 80 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3843171857533614, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,085] Trial 81 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.274958830821595, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,100] Trial 82 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5122425200204903, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,116] Trial 83 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3679495199545688, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,141] Trial 84 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4666741637238353, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,169] Trial 85 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4452743214195037, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,185] Trial 86 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4092227619285966, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,201] Trial 87 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.30822974726829444, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,217] Trial 88 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.24132341183147243, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,233] Trial 89 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.554200676695499, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,250] Trial 90 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.35871215633640385, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,266] Trial 91 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.27570494486661784, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,281] Trial 92 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.17187661953657274, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,297] Trial 93 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.13391607404350542, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,313] Trial 94 finished with value: 0.8324894514767933 and parameters: {'alpha': 0.5943684064575305, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,329] Trial 95 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3319250321073369, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,344] Trial 96 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.5184902117124516, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,369] Trial 97 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.3917434373202355, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,384] Trial 98 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.4216170898039568, 'class_weight': None}. Best is trial 2 with value: 0.8350210970464136.
[I 2026-06-24 19:35:48,400] Trial 99 finished with value: 0.8350210970464136 and parameters: {'alpha': 0.18905077971545373, 'class_weight': 'balanced'}. Best is trial 2 with value: 0.8350210970464136.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
2,2,0.835021,2026-06-24 19:35:46.805010,2026-06-24 19:35:46.821090,0 days 00:00:00.016080,0.445340,balanced,COMPLETE
6,6,0.835021,2026-06-24 19:35:46.868502,2026-06-24 19:35:46.883234,0 days 00:00:00.014732,0.398981,balanced,COMPLETE
5,5,0.835021,2026-06-24 19:35:46.850603,2026-06-24 19:35:46.867999,0 days 00:00:00.017396,0.474322,None,COMPLETE
4,4,0.835021,2026-06-24 19:35:46.836310,2026-06-24 19:35:46.850603,0 days 00:00:00.014293,0.561222,None,COMPLETE
33,33,0.835021,2026-06-24 19:35:47.307807,2026-06-24 19:35:47.322952,0 days 00:00:00.015145,0.414972,balanced,COMPLETE

##### Tryout best params

In [33]:
ridge_recall_optimized_model = RidgeClassifier(alpha=0.039558, class_weight='balanced', random_state=random_state)
ridge_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (Recall Optimized)')

              precision    recall  f1-score   support

           0       0.89      0.99      0.94        99
           1       0.99      0.88      0.93        98

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197

##### F1 optimized

In [34]:
def objective(trial):
    alpha = trial.suggest_float("alpha", 0.001, 1.0)
    class_weight = trial.suggest_categorical("class_weight", ['balanced', None])
    
    model = RidgeClassifier(
        class_weight=class_weight,
        alpha=alpha,
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=100)

ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_ridge_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_ridge_unscaled_f1_optuna_results)

[I 2026-06-24 19:35:48,437] A new study created in memory with name: no-name-bd43d1ec-76a2-42d5-9b1b-d5478ef749a6
[I 2026-06-24 19:35:48,451] Trial 0 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6887128400543996, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8968032437415377.
[I 2026-06-24 19:35:48,466] Trial 1 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3836215244809348, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,481] Trial 2 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4879508585697073, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,497] Trial 3 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.34050341394504147, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,519] Trial 4 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2953653812412449, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,534] Trial 5 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.7683388948658794, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,550] Trial 6 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.7661098362940976, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,566] Trial 7 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5479518775514844, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,581] Trial 8 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2522104130620245, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,597] Trial 9 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.5605693254771152, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,612] Trial 10 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.97332300642455, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,628] Trial 11 finished with value: 0.8970408743592326 and parameters: {'alpha': 0.0320805600888352, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,644] Trial 12 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.405803818735096, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,660] Trial 13 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.15808131480972049, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,676] Trial 14 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4720184104016639, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,691] Trial 15 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.143962698808967, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,707] Trial 16 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6236793510004196, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,722] Trial 17 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.471123207182117, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,737] Trial 18 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.9067385845838158, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,753] Trial 19 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.38850373697796386, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,769] Trial 20 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.22495577175599624, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,785] Trial 21 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3640133125803875, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,800] Trial 22 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3564795323900595, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,816] Trial 23 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.46397420004811385, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,832] Trial 24 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.31195754493020994, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,848] Trial 25 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.164182113392568, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,863] Trial 26 finished with value: 0.8970408743592326 and parameters: {'alpha': 0.024435328068160123, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,878] Trial 27 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6145863216565278, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,894] Trial 28 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.42324682284854187, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,909] Trial 29 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.5516283680335377, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,925] Trial 30 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2295727432394703, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,940] Trial 31 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.27446066902229826, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,956] Trial 32 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3069720894502013, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,971] Trial 33 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.707953156840675, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:48,987] Trial 34 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3356509566517078, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,004] Trial 35 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.1049513720281377, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,020] Trial 36 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5153499277442741, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,035] Trial 37 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4255855925933427, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,051] Trial 38 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.20532373443776522, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,067] Trial 39 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6079205841425914, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,082] Trial 40 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2876253780180678, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,097] Trial 41 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5333277153934851, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,114] Trial 42 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.7823160870877324, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,130] Trial 43 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4507252687833664, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,145] Trial 44 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6741680386074154, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,161] Trial 45 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.38820345988408433, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,176] Trial 46 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.49959045992608686, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,191] Trial 47 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5615491206222567, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,206] Trial 48 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.09338474833768934, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,222] Trial 49 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.34990207631096976, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,238] Trial 50 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.5826651031832327, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,253] Trial 51 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2804195567098542, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,268] Trial 52 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.24203861472315283, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,283] Trial 53 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.48440769970102554, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,299] Trial 54 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.38611795231340085, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,314] Trial 55 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.17980399633857824, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,330] Trial 56 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.44219348696480826, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,346] Trial 57 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.253164390633205, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,370] Trial 58 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6628641390874701, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,385] Trial 59 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3251162971895438, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,401] Trial 60 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.39593538646921544, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,417] Trial 61 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.41428267170856, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,432] Trial 62 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3583379485337863, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,448] Trial 63 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.47866387733437543, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,467] Trial 64 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.31656540982256315, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,483] Trial 65 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.20231746190731892, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,498] Trial 66 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5170897043846555, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,514] Trial 67 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.27053137682022216, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,540] Trial 68 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.1129816543582996, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,554] Trial 69 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3823947629247289, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,569] Trial 70 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4499454654359819, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,585] Trial 71 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.12861621184626115, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,600] Trial 72 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.08224778512665248, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,615] Trial 73 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.16760139575082733, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,631] Trial 74 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2157404329550593, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,646] Trial 75 finished with value: 0.8970408743592326 and parameters: {'alpha': 0.04828323998331016, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,667] Trial 76 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3027707938073715, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,682] Trial 77 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3505848340961331, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,697] Trial 78 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4067068086163131, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,713] Trial 79 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2483484240676792, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,738] Trial 80 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.14929811161070902, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,753] Trial 81 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5616629604395538, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,768] Trial 82 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4992838144952713, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,784] Trial 83 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4546981564861903, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,800] Trial 84 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.5367285910280758, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,816] Trial 85 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.9677840599846996, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,831] Trial 86 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.4296290412607424, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,847] Trial 87 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.6365100108997501, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,866] Trial 88 finished with value: 0.8968032437415377 and parameters: {'alpha': 0.5913433708635953, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,882] Trial 89 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3678526116786555, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,898] Trial 90 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.29571720535581325, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,913] Trial 91 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.328242700693738, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,939] Trial 92 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.06495997424841499, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,955] Trial 93 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.1857543014156544, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,970] Trial 94 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.47693234553596775, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:49,987] Trial 95 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.1354100937884578, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:50,002] Trial 96 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.2672412728468746, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:50,018] Trial 97 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.41631899481850043, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:50,034] Trial 98 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.22082902250915168, 'class_weight': None}. Best is trial 1 with value: 0.8982690274059969.
[I 2026-06-24 19:35:50,051] Trial 99 finished with value: 0.8982690274059969 and parameters: {'alpha': 0.3430052337864574, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8982690274059969.

,number,value,datetime_start,datetime_complete,duration,params_alpha,params_class_weight,state
1,1,0.898269,2026-06-24 19:35:48.451034,2026-06-24 19:35:48.466025,0 days 00:00:00.014991,0.383622,None,COMPLETE
2,2,0.898269,2026-06-24 19:35:48.466025,2026-06-24 19:35:48.481757,0 days 00:00:00.015732,0.487951,None,COMPLETE
3,3,0.898269,2026-06-24 19:35:48.481757,2026-06-24 19:35:48.497830,0 days 00:00:00.016073,0.340503,balanced,COMPLETE
4,4,0.898269,2026-06-24 19:35:48.497830,2026-06-24 19:35:48.519195,0 days 00:00:00.021365,0.295365,balanced,COMPLETE
35,35,0.898269,2026-06-24 19:35:48.987945,2026-06-24 19:35:49.004006,0 days 00:00:00.016061,0.104951,balanced,COMPLETE

##### Tryout best params

In [35]:
ridge_f1_optimized_model = RidgeClassifier(alpha=0.364826, class_weight='balanced', random_state=random_state)
ridge_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = ridge_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Ridge Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.89      0.99      0.94        99
           1       0.99      0.88      0.93        98

    accuracy                           0.93       197
   macro avg       0.94      0.93      0.93       197
weighted avg       0.94      0.93      0.93       197

#### Lasso Logistic Regression

In [36]:
# We can only tune the C (float) and Class_weight to tryout balanced.

In [37]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='recall',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15, n_jobs=-1)

lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_recall_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_recall_optuna_results)

[I 2026-06-24 19:35:50,102] A new study created in memory with name: no-name-9feea818-dd95-48bc-8816-891772453b65
[I 2026-06-24 19:35:50,170] Trial 2 finished with value: 0.8857189224277832 and parameters: {'C': 0.6518758124587234, 'Class_weight': None}. Best is trial 2 with value: 0.8857189224277832.
[I 2026-06-24 19:35:50,171] Trial 1 finished with value: 0.8806556312885426 and parameters: {'C': 0.2931630479904749, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8857189224277832.
[I 2026-06-24 19:35:50,201] Trial 11 finished with value: 0.7969165855241804 and parameters: {'C': 0.02974122152593529, 'Class_weight': None}. Best is trial 2 with value: 0.8857189224277832.
[I 2026-06-24 19:35:50,202] Trial 14 finished with value: 0.8375527426160339 and parameters: {'C': 0.05145403021232699, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.8857189224277832.
[I 2026-06-24 19:35:50,202] Trial 12 finished with value: 0.8933138591366439 and parameters: {'C': 0.9168408011523447, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,202] Trial 13 finished with value: 0.8857189224277832 and parameters: {'C': 0.5855918531959527, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,202] Trial 6 finished with value: 0.8781239857189224 and parameters: {'C': 0.24045637899309788, 'Class_weight': None}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,203] Trial 3 finished with value: 0.8933138591366439 and parameters: {'C': 0.9163383316035996, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,203] Trial 5 finished with value: 0.8907822135670237 and parameters: {'C': 0.8216678600096088, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,203] Trial 0 finished with value: 0.8882505679974034 and parameters: {'C': 0.5142578474179105, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,203] Trial 4 finished with value: 0.865465757870821 and parameters: {'C': 0.11499506412762758, 'Class_weight': None}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,203] Trial 9 finished with value: 0.8882505679974034 and parameters: {'C': 0.7365820514394489, 'Class_weight': 'balanced'}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,204] Trial 10 finished with value: 0.8933138591366439 and parameters: {'C': 0.8978634390747225, 'Class_weight': None}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,204] Trial 7 finished with value: 0.8781239857189224 and parameters: {'C': 0.2252673605580948, 'Class_weight': None}. Best is trial 12 with value: 0.8933138591366439.
[I 2026-06-24 19:35:50,204] Trial 8 finished with value: 0.8933138591366439 and parameters: {'C': 0.8717023776711866, 'Class_weight': None}. Best is trial 12 with value: 0.8933138591366439.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
3,3,0.893314,2026-06-24 19:35:50.108121,2026-06-24 19:35:50.203116,0 days 00:00:00.094995,0.916338,balanced,COMPLETE
10,10,0.893314,2026-06-24 19:35:50.116627,2026-06-24 19:35:50.204117,0 days 00:00:00.087490,0.897863,None,COMPLETE
8,8,0.893314,2026-06-24 19:35:50.114627,2026-06-24 19:35:50.204117,0 days 00:00:00.089490,0.871702,None,COMPLETE
12,12,0.893314,2026-06-24 19:35:50.120793,2026-06-24 19:35:50.202117,0 days 00:00:00.081324,0.916841,balanced,COMPLETE
5,5,0.890782,2026-06-24 19:35:50.110628,2026-06-24 19:35:50.203116,0 days 00:00:00.092488,0.821668,balanced,COMPLETE

In [38]:
def objective(trial):
    c = trial.suggest_float("C", 0.001, 1.0)
    class_weight = trial.suggest_categorical("Class_weight", ['balanced', None])
    
    model = LogisticRegression(
        penalty='l1', # Lasso
        class_weight=class_weight,
        C=c,
        solver='liblinear',
        random_state=random_state
    )
    
    scores = cross_val_score(
        model, 
        X=X_train_scaled, 
        y=y_train, 
        cv=cv,
        scoring='f1',
        n_jobs=-1,
    )
    recall = scores.mean()
    
    return recall


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=15)

lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False)
top_5_lasso_unscaled_f1_optuna_results = study.trials_dataframe().sort_values("value", ascending=False).head(5)
display(top_5_lasso_unscaled_f1_optuna_results)

[I 2026-06-24 19:35:50,235] A new study created in memory with name: no-name-c6b7cefb-10c7-4242-81c4-4db515b589d2
[I 2026-06-24 19:35:50,251] Trial 0 finished with value: 0.9236402061329537 and parameters: {'C': 0.26470429767396964, 'Class_weight': None}. Best is trial 0 with value: 0.9236402061329537.
[I 2026-06-24 19:35:50,271] Trial 1 finished with value: 0.9189235607225996 and parameters: {'C': 0.13515677287381883, 'Class_weight': 'balanced'}. Best is trial 0 with value: 0.9236402061329537.
[I 2026-06-24 19:35:50,298] Trial 2 finished with value: 0.9252932469235157 and parameters: {'C': 0.3681540561271384, 'Class_weight': 'balanced'}. Best is trial 2 with value: 0.9252932469235157.
[I 2026-06-24 19:35:50,314] Trial 3 finished with value: 0.9304212171893221 and parameters: {'C': 0.6723940063747261, 'Class_weight': None}. Best is trial 3 with value: 0.9304212171893221.
[I 2026-06-24 19:35:50,329] Trial 4 finished with value: 0.9320368539392762 and parameters: {'C': 0.8002068029038181, 'Class_weight': 'balanced'}. Best is trial 4 with value: 0.9320368539392762.
[I 2026-06-24 19:35:50,345] Trial 5 finished with value: 0.9304212171893221 and parameters: {'C': 0.6992530753287054, 'Class_weight': None}. Best is trial 4 with value: 0.9320368539392762.
[I 2026-06-24 19:35:50,360] Trial 6 finished with value: 0.9090093727656902 and parameters: {'C': 0.05269712908205558, 'Class_weight': None}. Best is trial 4 with value: 0.9320368539392762.
[I 2026-06-24 19:35:50,376] Trial 7 finished with value: 0.9320368539392762 and parameters: {'C': 0.8085555947644111, 'Class_weight': 'balanced'}. Best is trial 4 with value: 0.9320368539392762.
[I 2026-06-24 19:35:50,393] Trial 8 finished with value: 0.9334686212770839 and parameters: {'C': 0.8759334734470686, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.9334686212770839.
[I 2026-06-24 19:35:50,408] Trial 9 finished with value: 0.9316762421689898 and parameters: {'C': 0.43846152740391203, 'Class_weight': 'balanced'}. Best is trial 8 with value: 0.9334686212770839.
[I 2026-06-24 19:35:50,424] Trial 10 finished with value: 0.933644059873575 and parameters: {'C': 0.9647954729109409, 'Class_weight': 'balanced'}. Best is trial 10 with value: 0.933644059873575.
[I 2026-06-24 19:35:50,439] Trial 11 finished with value: 0.9350372487280643 and parameters: {'C': 0.9944273527886037, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.9350372487280643.
[I 2026-06-24 19:35:50,467] Trial 12 finished with value: 0.933644059873575 and parameters: {'C': 0.9772015775860627, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.9350372487280643.
[I 2026-06-24 19:35:50,482] Trial 13 finished with value: 0.933644059873575 and parameters: {'C': 0.9854512864848374, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.9350372487280643.
[I 2026-06-24 19:35:50,498] Trial 14 finished with value: 0.9304212171893221 and parameters: {'C': 0.5944782117362639, 'Class_weight': 'balanced'}. Best is trial 11 with value: 0.9350372487280643.

,number,value,datetime_start,datetime_complete,duration,params_C,params_Class_weight,state
11,11,0.935037,2026-06-24 19:35:50.424098,2026-06-24 19:35:50.439543,0 days 00:00:00.015445,0.994427,balanced,COMPLETE
10,10,0.933644,2026-06-24 19:35:50.408956,2026-06-24 19:35:50.424098,0 days 00:00:00.015142,0.964795,balanced,COMPLETE
12,12,0.933644,2026-06-24 19:35:50.439543,2026-06-24 19:35:50.467171,0 days 00:00:00.027628,0.977202,balanced,COMPLETE
13,13,0.933644,2026-06-24 19:35:50.467171,2026-06-24 19:35:50.482206,0 days 00:00:00.015035,0.985451,balanced,COMPLETE
8,8,0.933469,2026-06-24 19:35:50.376974,2026-06-24 19:35:50.393088,0 days 00:00:00.016114,0.875933,balanced,COMPLETE

##### Tryout best params

In [39]:
lasso_recall_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.248927, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_recall_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_recall_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (Recall Optimized)')

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

              precision    recall  f1-score   support

           0       0.94      0.99      0.97        99
           1       0.99      0.94      0.96        98

    accuracy                           0.96       197
   macro avg       0.97      0.96      0.96       197
weighted avg       0.97      0.96      0.96       197

In [40]:
lasso_f1_optimized_model = LogisticRegression(
    penalty='l1', # Lasso
    C=0.496023, 
    class_weight=None,
    solver='saga',
    random_state=random_state
)
lasso_f1_optimized_model.fit(X_train_scaled, y_train)
y_pred = lasso_f1_optimized_model.predict(X_test_scaled)
print(classification_report(y_true=y_test, y_pred=y_pred))
report = classification_report(y_true=y_test, y_pred=y_pred, output_dict=True)
df_temp = pd.DataFrame(report).transpose()

classification_reports.append(df_temp)
classification_report_keys.append('Lasso Classifier (F1 Optimized)')

              precision    recall  f1-score   support

           0       0.95      0.99      0.97        99
           1       0.99      0.95      0.97        98

    accuracy                           0.97       197
   macro avg       0.97      0.97      0.97       197
weighted avg       0.97      0.97      0.97       197

c:\Users\caleb\anaconda3\envs\iris-fisher\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

### Conclusions

In [41]:
pd.concat(classification_reports, keys=classification_report_keys)

                                                      precision    recall  \
Baseline Logistic Regression            0              0.958333  0.929293
                                        1              0.930693  0.959184
                                        accuracy       0.944162  0.944162
                                        macro avg      0.944513  0.944238
                                        weighted avg   0.944583  0.944162
Baseline Ridge Classifier               0              0.890909  0.989899
                                        1              0.988506  0.877551
                                        accuracy       0.934010  0.934010
                                        macro avg      0.939707  0.933725
                                        weighted avg   0.939460  0.934010
Baseline L1 (Lasso) Logistic Regression 0              0.949495  0.949495
                                        1              0.948980  0.948980
                                        accuracy       0.949239  0.949239
                                        macro avg      0.949237  0.949237
                                        weighted avg   0.949239  0.949239
Logistic Regression (Recall Optimized)  0              0.950980  0.979798
                                        1              0.978947  0.948980
                                        accuracy       0.964467  0.964467
                                        macro avg      0.964964  0.964389
                                        weighted avg   0.964893  0.964467
Logistic Regression (F1 Optimized)      0              0.950980  0.979798
                                        1              0.978947  0.948980
                                        accuracy       0.964467  0.964467
                                        macro avg      0.964964  0.964389
                                        weighted avg   0.964893  0.964467
Ridge Classifier (Recall Optimized)     0              0.890909  0.989899
                                        1              0.988506  0.877551
                                        accuracy       0.934010  0.934010
                                        macro avg      0.939707  0.933725
                                        weighted avg   0.939460  0.934010
Ridge Classifier (F1 Optimized)         0              0.890909  0.989899
                                        1              0.988506  0.877551
                                        accuracy       0.934010  0.934010
                                        macro avg      0.939707  0.933725
                                        weighted avg   0.939460  0.934010
Lasso Classifier (Recall Optimized)     0              0.942308  0.989899
                                        1              0.989247  0.938776
                                        accuracy       0.964467  0.964467
                                        macro avg      0.965778  0.964337
                                        weighted avg   0.965658  0.964467
Lasso Classifier (F1 Optimized)         0              0.951456  0.989899
                                        1              0.989362  0.948980
                                        accuracy       0.969543  0.969543
                                        macro avg      0.970409  0.969439
                                        weighted avg   0.970313  0.969543

                                                      f1-score     support
Baseline Logistic Regression            0             0.943590   99.000000
                                        1             0.944724   98.000000
                                        accuracy      0.944162    0.944162
                                        macro avg     0.944157  197.000000
                                        weighted avg  0.944154  197.000000
Baseline Ridge Classifier               0             0.937799   99.000000
                                        1             0.929730   98.000000
                                        accuracy      0.934010    0.934010
                                        macro avg     0.933764  197.000000
                                        weighted avg  0.933785  197.000000
Baseline L1 (Lasso) Logistic Regression 0             0.949495   99.000000
                                        1             0.948980   98.000000
                                        accuracy      0.949239    0.949239
                                        macro avg     0.949237  197.000000
                                        weighted avg  0.949239  197.000000
Logistic Regression (Recall Optimized)  0             0.965174   99.000000
                                        1             0.963731   98.000000
                                        accuracy      0.964467    0.964467
                                        macro avg     0.964452  197.000000
                                        weighted avg  0.964456  197.000000
Logistic Regression (F1 Optimized)      0             0.965174   99.000000
                                        1             0.963731   98.000000
                                        accuracy      0.964467    0.964467
                                        macro avg     0.964452  197.000000
                                        weighted avg  0.964456  197.000000
Ridge Classifier (Recall Optimized)     0             0.937799   99.000000
                                        1             0.929730   98.000000
                                        accuracy      0.934010    0.934010
                                        macro avg     0.933764  197.000000
                                        weighted avg  0.933785  197.000000
Ridge Classifier (F1 Optimized)         0             0.937799   99.000000
                                        1             0.929730   98.000000
                                        accuracy      0.934010    0.934010
                                        macro avg     0.933764  197.000000
                                        weighted avg  0.933785  197.000000
Lasso Classifier (Recall Optimized)     0             0.965517   99.000000
                                        1             0.963351   98.000000
                                        accuracy      0.964467    0.964467
                                        macro avg     0.964434  197.000000
                                        weighted avg  0.964440  197.000000
Lasso Classifier (F1 Optimized)         0             0.970297   99.000000
                                        1             0.968750   98.000000
                                        accuracy      0.969543    0.969543
                                        macro avg     0.969524  197.000000
                                        weighted avg  0.969527  197.000000

The best model is the Lasso with macro avg precision 0.965778 recall 0.964337 and f1 0.964434. All models performed very well though on this dataset. Lasso could have been better than log reg due to multicollinearity

In [42]:
import numpy as np

pd.set_option('display.max_rows', None)

coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Ridge_Coef': ridge_f1_optimized_model.coef_,
})

# Sort features by the absolute size of their coefficients
coef_df['Abs_Coefficient'] = np.abs(coef_df['Ridge_Coef'])
coef_df = coef_df.sort_values(by='Abs_Coefficient', ascending=False)
coef_df

   Feature  Ridge_Coef  Abs_Coefficient
7       V7    0.521043         0.521043
14     V14   -0.510886         0.510886
4       V4    0.446034         0.446034
1       V1   -0.331711         0.331711
10     V10   -0.212063         0.212063
18     V18    0.200497         0.200497
8       V8   -0.178609         0.178609
17     V17   -0.131455         0.131455
3       V3   -0.119278         0.119278
23     V23   -0.112265         0.112265
2       V2   -0.105656         0.105656
21     V21    0.105656         0.105656
28     V28    0.102367         0.102367
12     V12    0.083382         0.083382
22     V22    0.077000         0.077000
11     V11   -0.072025         0.072025
13     V13   -0.067813         0.067813
5       V5   -0.060082         0.060082
0     Time   -0.053634         0.053634
19     V19    0.048391         0.048391
20     V20    0.048154         0.048154
27     V27   -0.042326         0.042326
26     V26   -0.041507         0.041507
9       V9    0.035652         0.035652
25     V25   -0.026304         0.026304
16     V16    0.025702         0.025702
15     V15   -0.022220         0.022220
24     V24    0.016797         0.016797
29  Amount   -0.007263         0.007263
6       V6   -0.005622         0.005622

In [43]:
len(coef_df[coef_df['Abs_Coefficient'] == 0])

0

We can see 0 features coefs get shrunk to 0 by the Ridge model. All features must be at least slightly important

In [44]:
coefficients = lasso_f1_optimized_model.coef_[0]

# 3. Create a DataFrame to map features to their coefficients
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': coefficients
})

# 4. VIEW RETAINED FEATURES (Coefficient is NOT 0)
selected_features = coef_df[coef_df['Coefficient'] != 0]
print("Features Selected by Lasso:")
print(selected_features)

# 5. VIEW REJECTED FEATURES (Coefficient is exactly 0)
dropped_features = coef_df[coef_df['Coefficient'] == 0]
print("\nFeatures Ignored by Lasso:")
print(dropped_features['Feature'].tolist())

Features Selected by Lasso:
   Feature  Coefficient
0     Time    -0.054337
3       V3    -0.004034
4       V4     2.157277
5       V5     0.137784
6       V6    -0.116894
8       V8    -0.891354
9       V9    -0.192883
10     V10    -1.167566
11     V11     0.474983
12     V12    -1.297026
13     V13    -0.316520
14     V14    -2.410177
18     V18     0.177864
20     V20    -0.201561
22     V22     0.410333
23     V23    -0.265760
25     V25    -0.033709
26     V26    -0.040076
27     V27    -0.242138
28     V28     0.277115
29  Amount     0.384781

Features Ignored by Lasso:
['V1', 'V2', 'V7', 'V15', 'V16', 'V17', 'V19', 'V21', 'V24']

We can see Lasso also removed 9 features during feature selection